### ISSUE TITLE
Activity stream problem: "Cannot cast a filtered stream on this system"

### ISSUE THREAD

**Issue by Nek-** [platformsh/platformsh-cli#1027]
When I try the command `platform environment:activate --project=project_id --parent=develop branch -vvv`, I get this issue:

```
Waiting for the activity xxx (Nek activated environment feature/assets-packages):

[-->-------------------------] 3 secs (in progress)
Warning: stream_select(): Cannot cast a filtered stream on this system in phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php on line 203

Fatal error: Uncaught ValueError: No stream arrays were passed in phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php:203
Stack trace:
#0 phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php(203): stream_select(Array, Array, Array, 0, 200000)
#1 phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php(124): Platformsh\Cli\Service\ActivityMonitor->canRead(Resource id #810, 200000)
#2 phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php(252): Platformsh\Cli\Service\ActivityMonitor->waitAndLog(Object(Platformsh\Client\Model\Activity))
#3 phar:///Users/nek/.platformsh/bin/platform/src/Command/Environment/EnvironmentActivateCommand.php(118): Platformsh\Cli\Service\ActivityMonitor->waitMultiple(Array, Object(Platformsh\Client\Model\Project))
#4 phar:///Users/nek/.platformsh/bin/platform/src/Command/Environment/EnvironmentActivateCommand.php(43): Platformsh\Cli\Command\Environment\EnvironmentActivateCommand->activateMultiple(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
#5 phar:///Users/nek/.platformsh/bin/platform/vendor/symfony/console/Command/Command.php(255): Platformsh\Cli\Command\Environment\EnvironmentActivateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///Users/nek/.platformsh/bin/platform/vendor/symfony/console/Application.php(1010): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///Users/nek/.platformsh/bin/platform/src/Application.php(297): Symfony\Component\Console\Application->doRunCommand(Object(Platformsh\Cli\Command\Environment\EnvironmentActivateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///Users/nek/.platformsh/bin/platform/vendor/symfony/console/Application.php(255): Platformsh\Cli\Application->doRunCommand(Object(Platformsh\Cli\Command\Environment\EnvironmentActivateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///Users/nek/.platformsh/bin/platform/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Users/nek/.platformsh/bin/platform/bin/platform(32): Symfony\Component\Console\Application->run()
#11 /Users/nek/.platformsh/bin/platform(10): require('phar:///Users/m...')
#12 {main}
  thrown in phar:///Users/nek/.platformsh/bin/platform/src/Service/ActivityMonitor.php on line 203
```

Another issue not-really-related to the cli is that when you try to create an environment while you cannot because you're out of the authorized number of environments deployed, it will create the environment anyway but it's broken. (it would be nice if nothing happen)

**Comment by pjcdawkins** [comment]
Could you give me your PHP and system version? Is this macOS?

> when you try to create an environment while you cannot because you're out of the authorized number of environments deployed, it will create the environment anyway but it's broken

Hm that sounds new. I'll report the issue for the environments API (internally).

**Comment by pjcdawkins** [comment]
> it will create the environment anyway but it's broken

how is it "broken"? it's supposed to create an "inactive" environment in that case, i.e. just a Git branch

**Comment by Nek-** [comment]
> how is it "broken"? it's supposed to create an "inactive" environment in that case, i.e. just a Git branch

The environment is created with no build and no possibility to do anything except dropping it.

Redeploying - after removing another environment - doesn't work either. But it may be related to another issue we have on our project activate broken environments. _I assume you can ignore it_.

**Comment by pjcdawkins** [comment]
> The environment is created with no build and no possibility to do anything except dropping it.

OK, I think that's intentional, it's there as "inactive" / as a Git branch? It could then be "activated" but not "redeployed". The experience/communication could be improved, clearly.

**Comment by pjcdawkins** [comment]
> Uncaught ValueError: No stream arrays were passed

This sounds impossible, maybe even a PHP 8 bug?

The backtrace says 

> ActivityMonitor->canRead(Resource id #810, 200000)

so that was called with a resource.

That method does:

https://github.com/platformsh/platformsh-cli/blob/9f91b23da3b8c91955dd9d1802490153c0456f2c/src/Service/ActivityMonitor.php#L199-L202

so it must be passing a stream resource...

I'll try to reproduce on various PHP versions

**Comment by Nek-** [comment]
> > The environment is created with no build and no possibility to do anything except dropping it.
> 
> OK, I think that's intentional, it's there as "inactive" / as a Git branch? It could then be "activated" but not "redeployed". The experience/communication could be improved, clearly.

No, it cannot be activated because it is already. (it's not possible to do such action from the UI (the interface makes sense), that's why I report it as issue)

**Comment by pjcdawkins** [comment]
> No, it cannot be activated because it is already. (it's not possible to do such action from the UI (the interface makes sense), that's why I report it as issue)

We'll think about this... it's possible this is project-specific - you could send me the project ID at `patrick@platform.sh` or submit a ticket - although it sounds like you have a ticket open already.

**Comment by Nek-** [comment]
> > No, it cannot be activated because it is already. (it's not possible to do such action from the UI (the interface makes sense), that's why I report it as issue)
> 
> We'll think about this... it's possible this is project-specific - you could send me the project ID at `patrick@platform.sh` or submit a ticket - although it sounds like you have a ticket open already.

it is not project specific (we have ~20 projects). I didn't open a ticket about that. (but about deployment not working at all, it seems like you have a team on it)

**Comment by pjcdawkins** [comment]
It looks like the underlying PHP source code hasn't changed since at least 2003.

https://github.com/php/php-src/blob/643a727c37de0e87cf7b0fa9f422f527a308dd13/main/streams/cast.c#L296

As our `stream_select()` call works on PHP 5 and PHP 7, it's probably not true that this should be an error, so unfortunately I suspect this is an ancient bug that is now surfacing as an error in PHP 8 (because `ValueError` is now a thing).

**Comment by pjcdawkins** [comment]
This very old thing sheds some light

http://web.mit.edu/darwin/src/modules/apache_mod_php/php/README.STREAMS

> What if your extension needs to access the FILE* of a user level file pointer?
> You need to "cast" the stream into a FILE*,

> If you ask a socket stream for a FILE*, the abstraction will use fdopen to
create it for you.  Be warned that doing so may cause buffered data to be lost
if you mix ANSI stdio calls on the FILE* with php stream calls on the stream.

> If your system has the fopencookie function, php streams can synthesize a
FILE* on top of any stream, which is useful for SSL sockets, memory based
streams, data base streams etc. etc.
NOTE: There might be situations where this is not desireable, and we need to
provide a flag to inform the casting routine of this.

I suspect the "filter" on our stream is the TLS encryption, which obviously we need.

The `stream_select()` is here so that we can know when to read the stream (without blocking the progress bar updates).

**Comment by pjcdawkins** [comment]
@Nek- Please test #1036 ^

( easiest to use the instructions at https://pr-1036-7m3ihli-mpaw4nkgdwaea.eu-2.platformsh.site/ )
