### ISSUE TITLE
Installer fails when behind proxy

### ISSUE THREAD

**Issue by rokkie** [platformsh/platformsh-cli#1035]
While trying to create a docker image with the CLI using the command
```dockerfile
RUN curl -sS https://platform.sh/cli/installer | php
```
I got the following error:
```
Warning: file_get_contents(https://platform.sh/cli/manifest.json): failed to open stream: Unable to find the socket transport "http" - did you forget to enable it when you configured PHP? in Standard input code on line 355
```

A quick search pointed out that this was probably because of running behind a proxy, which made sense since this is indeed the case.

The composer installer seems to account for this:
```php
// http(s):// is not supported in proxy
$proxyURL = str_replace(array('http://', 'https://'), array('tcp://', 'ssl://'), $proxyURL);
```
which seems to do the trick since
```dockerfile
RUN curl -sS https://getcomposer.org/installer | php
```
(in the same dockerfile) works as expected.

Maybe something similar can be done here?

**Comment by pjcdawkins** [comment]
Hi @rokkie, thanks for this issue. If you have time, could you please test the installer in the PR above? it would be:

```Dockerfile
RUN curl -sfS https://raw.githubusercontent.com/pjcdawkins/platformsh-cli/proxy-replace-http/dist/installer.php | php
```

**Comment by rokkie** [comment]
@pjcdawkins Works!

**Comment by rokkie** [comment]
Maybe this fixes #952 as well

**Comment by pjcdawkins** [comment]
Good point - yes probably.

The installer change is now deployed.

**Comment by rokkie** [comment]
Thanks for the quick response!
