### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by koko236** [platformsh/platformsh-cli#1053]
In help message for `environment:httpaccess` command there seems to be a mistake.

It says: 
```
Restrict access to only one IP address:
   platform httpaccess --access deny:any --access allow:69.208.1.192
```
when AFAIK the order should be reveresed:
```
platform httpaccess --access allow:69.208.1.192 --access deny:any
```
as per online docs here:
![image](https://user-images.githubusercontent.com/741399/117124636-e398ac80-ad98-11eb-93ca-9e1295591f8b.png)

I tested both ways and it seems to me that the second works as intended.

**Comment by pjcdawkins** [comment]
Right, thank you!
