### ISSUE TITLE
Mac M1 processor on Docker: Segmentation fault on db:dump and user:list

### ISSUE THREAD

**Issue by rfay** [platformsh/platformsh-cli#1063]
I'm seeing a SEGV on db:dump (Debian Buster, on ddev). It's worked fine for a few months with various versions of ddev and various versions of platformsh-cli, but now I just see the Segmentation Fault no matter what version of platformsh-cli I use. I've tried 3.66.3 (which is where I started getting it) but I manually installed 3.65.4 and saw the same thing with that. 3.66.1 has the same behavior, same SEGV, but it has definitely worked and passed tests before.  Using same PHP version as previously, 7.4.18, same build. 

`platform user:list` also does a SEGV

```
platform db:dump -vvv --yes --gzip --file=/var/www/html/.ddev/.downloads/db.sql.gz --project=lago3j23xu2w6 --environment=master
DEBUG Selected project: lago3j23xu2w6
Segmentation fault
```

Is this a result of something on the server end perhaps? The project it's acting on is running fine.

Suggestions how to debug a SEGV here?

Edit: List of some commands that SEGV:
* user:list
* db:dump
* route:list
* environment:list
* commit:list
* domain:list

**Comment by pjcdawkins** [comment]
HI @rfay, the only segfault I've encountered in the CLI so far has a workaround here:
https://github.com/platformsh/platformsh-cli/blob/3.x/bin/platform#L9-L20
But that was related to `pcntl_fork()` which is not involved in the commands you mention.

The `db:dump` command and `user:list` do quite different things, so I'm surprised you find the problem in those in particular. The former runs an SSH command (via `proc_open()`) and that probably involves writing to the filesystem, the latter just runs API calls. But both probably try writing to the local filesystem (for a cache) and both interact with curl, assuming you have the PHP curl extension enabled.

Some debugging ideas:

* `strace` on the process
* set `PLATFORMSH_CLI_DEBUG=1` to add curl debugging output. It implies `-vvv`. At least this might help to see at what point the bug occurs.
* disable the (filesystem) cache with `PLATFORMSH_CLI_DISABLE_CACHE=1`
* try disabling or enabling the php curl extension, or another optional/unnecessary PHP extension (xdebug perhaps?)

**Comment by rfay** [comment]
Thanks for the good ideas. This problem occurs in an image built for a PR that I suddenly am distrusting :) I certainly didn' tknow about PLATFORMSH_CLI_DEBUG or PLATFORMSH_CLI_DISABLE_CACHE, and strace is of course where I should have started.

**Comment by rfay** [comment]
OK, I think I've got it nailed down. It seems to happen on arm64 linux container running on the Mac M1. 

I thought I was going to have a full repro repository for you, but I'm doing better demonstrating it by stepping through existing docker images.

On a Mac M1 do this:
```
docker run -it --rm ubuntu:focal bash
apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl php 
curl -sSL -o /usr/local/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.66.3/platform.phar && chmod +x /usr/local/bin/platform
export PLATFORM_CLI_TOKEN=<yourtoken>
export PLATFORMSH_CLI_DEBUG=1
platform user:list
```

I think you'll find that it seems to be on cert validation

```
write(2, "<GET https://eu-3.platform.sh/ap"..., 75<GET https://eu-3.platform.sh/api/projects/lago3j23xu2w6/access> [CONNECT] ) = 75
write(2, "\n", 1
)                       = 1
fcntl(5, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(5, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x20ffff99f6907c} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@d3953f23601d:/# 
```

I was unable to recreate this scenario on an amd64 image, and was unable to recreate it running natively on the mac. So it seems to be a M1 processor + linux container problem.

I was able to recreate it with both Debian and Ubuntu images (on M1) though. And I was able to recreate it on more than one M1 machine.

**Comment by pjcdawkins** [comment]
If it's on cert validation, have you tried with + without php-curl? is it a PHP bug, or a php-curl extension bug? (I doubt it's a bug in curl itself)

I don't see anything unusual about the cert https://www.ssllabs.com/ssltest/analyze.html?d=eu%2d3.platform.sh&s=34.241.159.179&hideResults=on&latest

**Comment by pjcdawkins** [comment]
... after reading the output I see that's without php-curl, so it's a PHP bug. Try enabling the curl extension

**Comment by rfay** [comment]
With curl enabled, 

```
DEBUG Selected project: lago3j23xu2w6
*   Trying 34.241.159.179:443...
* TCP_NODELAY set
* Connected to eu-3.platform.sh (34.241.159.179) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=eu-3.platform.sh
*  start date: Jun  7 07:50:22 2021 GMT
*  expire date: Sep  5 07:50:22 2021 GMT
*  subjectAltName: host "eu-3.platform.sh" matched cert's "eu-3.platform.sh"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
Segmentation fault
```

I don't doubt it's a php bug. The odd thing is that I've experienced it with widely different php versions (using deb.sury.org or using the default ubuntu or debian repos)

**Comment by pjcdawkins** [comment]
So, different PHP versions and different CLI versions? the only thing in common is ARM / M1?

**Comment by rfay** [comment]
Yes, exactly. So it's probably a built-in PHP bug that only shows up on Linux with M1 processor. Just wish we had a clue how to create it in a simpler environment.

**Comment by rfay** [comment]
Interestingly enough, Acquia's acli also SEGVs exactly the same way on M1 Linux arm64 (and strace says in exactly the same context, right after accessing ssl certs). This sure is an interesting one. I wonder if it has to do with phar or box, which both use.

**Comment by rfay** [comment]
This seems to be a result of a problem with Debian 10 docker image and the related openssl on M1.

An obscure entry in the Docker for Mac 3.4.0 [release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-340) mentions 
> On Apple Silicon in native arm64 containers, older versions of libssl in debian:buster, ubuntu:20.04 and centos:8 will segfault when connected to some TLS servers, for example curl https://dl.yarnpkg.com. The bug is fixed in newer versions of libssl in debian:bullseye, ubuntu:21.04 and fedora:35

I built ddev's ddev-webserver with Debian Bullseye and it made this problem go away, along with the one on acli, along with the problem of `curl https://dl.yarnpkg.com`

**Comment by pjcdawkins** [comment]
Nice work tracking that down, and thanks for updating the issue here!
