### ISSUE TITLE
Login failing with SSL issues:

### ISSUE THREAD

**Issue by monckey100** [platformsh/platformsh-cli#1083]
PS C:\\Users\\GoodDay> platform  
Welcome to Platform.sh!

Loading projects...  
Authentication is required.

Log in via a browser? \[Y/n\]

 \[RuntimeException\]  
 Aborted.

  
PS C:\\Users\\GoodDay> platform -y  
Welcome to Platform.sh!

Loading projects...

  
 \[LoginRequiredException\]  
 Authentication is required.

 Please log in by running:  
     platform login

 To log in using an API token, run: platform auth:api-token-login

  
PS C:\\Users\\GoodDay> platform login  
Opened URL: http://127.0.0.1:5000  
Please use the browser to log in.

Help:  
 Leave this command running during login.  
 If you need to quit, use Ctrl+C.

Login information received. Verifying...

  
 \[RequestException\]  
 cURL error 60: SSL certificate problem: unable to get local issuer certificate

 \[RingException\]  
 cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by pjcdawkins** [comment]
Version 3.75.0 hopefully solves this. It was also reported in #754 and #990.
