### ISSUE TITLE
Feature Request: activity:list --exclude

### ISSUE THREAD

**Issue by raupie** [platformsh/platformsh-cli#1091]
Often crons can take up the activity list and it's difficult to filter them. It would be ideal to return ALL activity types EXCEPT for a specific type of activity (noisy activities) such as `cron`. 

Please consider adding an `--exclude` or `--exclude-type` for the `activity:list` function.

**Comment by pjcdawkins** [comment]
Done in v3.79.0 via https://github.com/platformsh/platformsh-cli/pull/1124

(with a TODO to pull the list of types from the API if/when that's available)
