### ISSUE TITLE
Command not found platform

### ISSUE THREAD

**Issue by Tonyobyo** [platformsh/platformsh-cli#1094]
Aside from ensuring I have the correct versions of PHP, Node, Git, etc. as per the Github requirements I run 

`curl -sS https://platform.sh/cli/installer | php`

which works correctly without any issue, but upon authenticating with `platform` terminal states the command isn't found.

Has anyone run into this and/or been able to solve this?

**Comment by pjcdawkins** [comment]
Hi @Tonyobyo I hope that means it's working for you, happy to help if not
