### ISSUE TITLE
Broken TTY after hitting CTRL+C on a choice question

### ISSUE THREAD

**Issue by nicolas-grekas** [platformsh/platformsh-cli#1105]
Eg if I run project:info while I'm not in a configured project, platform will show me the list of my project.
If I hit CTRL+C to quit the command, by bash TTY is broken: I cannot see what I type and I have to type `stty sane` blindly in my term to recover.

**Comment by pjcdawkins** [comment]
This is odd, PHP should be getting a SIGINT directly - what OS and PHP version?

**Comment by nicolas-grekas** [comment]
Might be related to https://github.com/symfony/symfony/issues/44045, I'll let you know.

**Comment by nicolas-grekas** [comment]
Should be fixed by https://github.com/symfony/symfony/pull/45109 hopefully.
