### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by nicolas-grekas** [platformsh/platformsh-cli#1110]
This is a duplicate of https://github.com/platformsh/platformsh-cli/issues/1079 but with new insights.

TL;DR: please enable non-ECDHE ciphers on api.platform.sh

While helping ppl migrate from SymfonyCloud to Platform.sh, I saw MANY ppl having this issue, "certificate has expired".

This happens on both Windows and Mac, and the reason is an outdated openssl lib.
Ppl using SymfonyCloud don't have this issue because the `symfony` binary embeds it's own SSL routines.
But ppl that use the `platform` binary use the system's openssl, and :boom:

While we might dream of telling ppl to upgrade, it's out of reach from a DX perspective.
The current situation gives a terrible experience to those ppl.

I dig a bit more to understand the root cause and here it is:

First, I reproduced the issue on a `wsl` on Windows 10.
Then, I realized that `composer` doesn't have the issue, which means that php is able to connect to both packagist.org and github.com.

Here is why: api.platform.sh supports only ECDHE ciphers, while packagist and github both also allow non-ECDHE ciphers. See below for details.

The solution is then simple: the TLS endpoint serving api.platform.sh should be reconfigured to allow the same ciphers as github.

A workaround in the `platform` client could be to use `openssl_get_cipher_methods()` to disable SSL verification if php doesn't support ECDHE ciphers. But it'd be a shame to go this way.

```
$> nmap --script ssl-enum-ciphers -p 443 api.platform.sh
[...]
]| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A
```

```
$> nmap --script ssl-enum-ciphers -p 443 api.github.com
[...]
]| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A

```

**Comment by pjcdawkins** [comment]
It sounds like a CA bundle problem not a cipher problem, and the difference may be that we use Let's Encrypt certificates (who did have a root expiring last year) widely, and presumably packagist and GitHub don't?

We could probably be more insistent about the packaged CA bundle on certain systems.

**Comment by pjcdawkins** [comment]
Actually can you please run some api command with debug output on, eg

```
platform pro:info -vvv
```

It should (with the latest version) print composer's debug output regarding CA bundle paths

**Comment by pjcdawkins** [comment]
This is not sufficiently documented yet in the CLI, but like in Composer, you can provide a different CA bundle path with any of these config options:

https://github.com/composer/ca-bundle/blob/4c679186f2aca4ab6a0f1b0b9cf9252decb44d0b/src/CaBundle.php#L74-L83

**Comment by nicolas-grekas** [comment]
You can trust me on this one, this is not related to the cabundle. I spent enough hours on it 😉

**Comment by nicolas-grekas** [comment]
About Let's encrypt, it's unrelated, here is the proof: the certificate chain for packagist.org also uses let's encrypt, and if you compare it with api.platform.sh's one, you'll see both certificates are exactly the same. Yet, packagist.org is reachable with those php binaries while api.platforh.sh is not. I also confirm that I already tried the various cabundles (system and composer/ca-bundle), this makes no difference (as should be obivous per the previous sentence).

For reference, I ran the nmap command on symfony.com, aka on certificates that YOU (PSH) generate, and they don't have the issue! (it'd be great to remove the C-level TLSv1 ciphers btw.)

```
nmap --script ssl-enum-ciphers -p 443 symfony.com
[...]
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|     compressors: 
|       NULL
|     cipher preference: server
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256-draft (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256-draft (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|     compressors: 
|       NULL
|     cipher preference: client
|_  least strength: C
```

**Comment by nicolas-grekas** [comment]
For reference, I'm running various binaries from https://windows.php.net/downloads/releases/archives/ in WSL.

With those binaries, forcing the fallback cert.pem from composer/ca-bundle and using `fopen()`:
- for api.platform.sh: works around the issue on PHP 5.6.11 *but fails* on PHP 5.6.10
- for repo.packagist.org: works around the issue on PHP 5.6.11 *works too* on PHP 5.6.10

Using the native `php` binary provided by my wsl, which is based on Ubuntu trusty, PHP 5.5.9:
- using fopen(): works for both api.platform.sh and repo.packagist.org, using either the system or the fallback ca-bundles

The only difference I can spot between api.platform.sh and repo.packagist.org is the list of ciphers.

My conclusion is thus that with the current cipher list, both the ca-bundle and the version of php/openssl play a role.
And that with packagist's cipher list (and github's), the ca-bundle and the version of php/openssl don't play a role anymore - things always work.

**Comment by nicolas-grekas** [comment]
For reference also, here is the script I played with (commenting/uncommenting line 4/7).

```php
<?php

$url = 'https://api.platform.sh';
$url = 'https://repo.packagist.org';

$otherLocations = [
    __DIR__.'/Downloads/composer/vendor/composer/ca-bundle/res/cacert.pem',
    '/etc/pki/tls/certs/ca-bundle.crt', // Fedora, RHEL, CentOS (ca-certificates package)
    '/etc/ssl/certs/ca-certificates.crt', // Debian, Ubuntu, Gentoo, Arch Linux (ca-certificates package)
    '/etc/ssl/ca-bundle.pem', // SUSE, openSUSE (ca-certificates package)
    '/usr/local/share/certs/ca-root-nss.crt', // FreeBSD (ca_root_nss_package)
    '/usr/ssl/certs/ca-bundle.crt', // Cygwin
    '/opt/local/share/curl/curl-ca-bundle.crt', // OS X macports, curl-ca-bundle package
    '/usr/local/share/curl/curl-ca-bundle.crt', // Default cURL CA bunde path (without --with-ca-bundle option)
    '/usr/share/ssl/certs/ca-bundle.crt', // Really old RedHat?
    '/etc/ssl/cert.pem', // OpenBSD
    '/usr/local/etc/ssl/cert.pem', // FreeBSD 10.x
    '/usr/local/etc/openssl/cert.pem', // OS X homebrew, openssl package
    '/usr/local/etc/openssl@1.1/cert.pem', // OS X homebrew, openssl@1.1 package
];

foreach ($otherLocations as $cert) {
    if (file_exists($cert)) {
        break;
    }
}

$h = fopen($url, 'r', false, $c = stream_context_create([
    'ssl' => [
        'SNI_enabled' => true,
        'capture_peer_cert_chain' => true,
        'capture_session_meta' => true,
        'verify_peer' => true,
        'cafile' => $cert,
    ],
]));

print_r(stream_context_get_options($c));
print_r(stream_get_meta_data($h));

$h = curl_init();
curl_setopt($h, CURLOPT_URL, $url);
curl_setopt($h, CURLOPT_SSL_VERIFYPEER, true);
curl_setopt($h, CURLOPT_CAINFO, $cert);
curl_exec($h);
```

**Comment by nicolas-grekas** [comment]
Looks like I was wrong about the cipher lists.
There is another difference, which is that packagist is using the "alternate chain" from Let'sencrypt while api.platform.sh is using the default chain.

See eg https://community.letsencrypt.org/t/long-default-and-short-alternate-certificate-chains-explained/162526 for some details about the difference.

The solution could then be to use the alt chain for api.platform.sh also.

**Comment by nicolas-grekas** [comment]
Using the alternate chain from LE definitely helps!

Now, curl is always able to connect to the host \o/

There is still a situation that doesn't work: on older versions of PHP (before June 2015), disabling curl (aka using fopen() ) makes the call to stg fail, while packagist works (with latest ca-bundle.)

> fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Could be worth trying the ciphers idea now, since that's the only diff that remains.
