### ISSUE TITLE
Return useful errors when cert addition fails

### ISSUE THREAD

**Issue by Kazanir** [platformsh/platformsh-cli#113]
We had a Zendesk ticket (#811) where the cert upload was failing because the private key being supplied had additional metadata attached and wasn't strictly RSA compliant. This is something we should be able to check for, and we should also grab the actual error from the Platform API and return it intelligently instead of just failing out and complaining about how the world is against us.

**Comment by pjcdawkins** [comment]
More error details are now reported from the API. I haven't seen a ticket about this, at least for a long time. Can this be closed?
