### ISSUE TITLE
cli should respect $PLATFORM_ENVIRONMENT and doesn't yet

### ISSUE THREAD

**Issue by rfay** [platformsh/platformsh-cli#1143]
It seems like platformsh-cli should use $PLATFORM_ENVIRONMENT as the default environment and just use it, but it doesn't - instead it prompts for an environment ID:

```
$ echo "PLATFORM_PROJECT=$PLATFORM_PROJECT PLATFORM_ENVIRONMENT=$PLATFORM_ENVIRONMENT"
PLATFORM_PROJECT=6j4ypl5iendqc PLATFORM_ENVIRONMENT=workshop-finished
$ platform ssh
Enter an environment ID (default: workshop): 

$ platform ssh -e $PLATFORM_ENVIRONMENT

 ___ _      _    __                    _    
| _ \ |__ _| |_ / _|___ _ _ _ __    __| |_  
|  _/ / _` |  _|  _/ _ \ '_| '  \ _(_-< ' \ 
|_| |_\__,_|\__|_| \___/_| |_|_|_(_)__/_||_|
                                            

 Welcome to Platform.sh.

 This is environment workshop-finished-fgyjnfq
```

**Comment by rfay** [comment]
Ah, I do see that PLATFORM_BRANCH gets the behavior I want:
```
$ echo "PLATFORM_ENVIRONMENT=$PLATFORM_ENVIRONMENT"
PLATFORM_ENVIRONMENT=workshop-finished
$ export PLATFORM_BRANCH=$PLATFORM_ENVIRONMENT
$ platform ssh
Warning:
An API token is set. Anyone with SSH access to this environment can read the token.
Please ensure the token only has strictly necessary access.


 ___ _      _    __                    _    
| _ \ |__ _| |_ / _|___ _ _ _ __    __| |_  
|  _/ / _` |  _|  _/ _ \ '_| '  \ _(_-< ' \ 
|_| |_\__,_|\__|_| \___/_| |_|_|_(_)__/_||_|
                                            

 Welcome to Platform.sh.

 This is environment workshop-finished-fgyjnfq
 of project 6j4ypl5iendqc.
```

**Comment by rfay** [comment]
Not completed... Shouldn't it be respected?

**Comment by pjcdawkins** [comment]
Sorry I don't understand "respected". The variable is something set on application environments. What's the use case?

**Comment by rfay** [comment]
So this issue was about platform CLI respecting PLATFORM_ENVIRONMENT. One would expect that it would know the environment because it was set in $PLATFORM_ENVIRONMENT. But the only env var it uses for the environment is $PLATFORM_BRANCH. PLATFORM_ENVIRONMENT (the logical thing to set this) seems to be ignored.

**Comment by pjcdawkins** [comment]
Unfortunately by usage in p.sh environments PLATFORM_ENVIRONMENT is the fairly obscure hashed machine name, not a git branch name, so it's not something a user would be expected to configure. Happy to add something but it increases the already numerous sources of things that cause an environment to be automatically selected, which is a source of confusion, so the use case needs to outweigh that, and it's not clear this would/should be used.
