### ISSUE TITLE
Provide better error message when git fetching without PHP

### ISSUE THREAD

**Issue by andriokha** [platformsh/platformsh-cli#1199]
I could be wrong, but it appears you need to have PHP in your path to be able to do a git fetch on a repo from a Platform env. I typically don't have any languages globally installed on my development machine although it does have git. When I try to do a fetch without PHP:

```
$ git fetch
somewhere@git.us-3.platform.sh: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

If I add PHP to the path it all just works. With debug info it looks like the culprit is the `platform ssh-cert:load` triggered by the `Match host` rule in the guts of some config file.
```
debug1: Reading configuration data /home/andy/.ssh/config
debug1: /home/andy/.ssh/config line 44: Applying options for *.platform.sh
debug3: /home/andy/.ssh/config line 45: Including file /home/andy/.platformsh/ssh/session.config depth 0
debug1: Reading configuration data /home/andy/.platformsh/ssh/session.config
debug1: /home/andy/.platformsh/ssh/session.config line 4: Applying options for *.platform.sh
debug3: /home/andy/.platformsh/ssh/session.config line 5: Including file /home/andy/.platformsh/.session/sess-cli-default/ssh/config depth 1
debug1: Reading configuration data /home/andy/.platformsh/.session/sess-cli-default/ssh/config
debug2: checking match for 'host "*.platform.sh" exec "platform ssh-cert:load --refresh-only --yes --quiet 2>/dev/null"' host git.us-3.platform.sh originally git.us-3.platform.sh
debug3: /home/andy/.platformsh/.session/sess-cli-default/ssh/config line 2: matched 'host "git.us-3.platform.sh"' 
debug1: Executing command: 'platform ssh-cert:load --refresh-only --yes --quiet 2>/dev/null'
debug3: command returned status 127
debug3: /home/andy/.platformsh/.session/sess-cli-default/ssh/config line 2: not matched 'exec "platform ssh-cert:load --refresh-only --yes --quiet 2>/dev/null"' 
debug2: match not found
```

I appreciate this is an edge case, but the error message really sent me running off in completely the wrong direction! I have no idea if you actually _can_ sanely handle errors from within a git `Match ... exec` rule, I can see STDERR has been deliberately squelched... but thought I'd throw in a request just in case. If not, I wonder if the requirement could be documented somewhere? (I'm half waiting for you to link me to the page where it's clearly written in bold :smiley:)

(Or am I just completely wrong to use git directly to fetch or push?)

Thanks!

**Comment by pjcdawkins** [comment]
A few thoughts so hope you don't mind I've numbered them:

1. As far as I can tell, this doesn't block SSH from proceeding as normal.
1. So, if you have SSH keys configured on your account (see `platform ssh-keys`) then the `git fetch` should work. Read further down in the SSH debug output to see which keys have been offered or rejected.
1. If you want to use `git fetch` without static SSH keys (in other words, with the "certificate" authentication provided by this CLI) then you'd need this `Match ... exec ...` to be working, as it ensures the certificate is fresh.
1. I probably wrote this with the assumption that, if you've run the CLI, then you'd be able to run it again during an SSH connection, via `platform` being in the path, which I agree is not a perfect assumption, but see (1).
1. You don't need PHP to run the CLI [anymore](https://platform.sh/blog/the-platformsh-cli-is-ready-to-golang/) (if you are happy to install it with Homebrew or from one of the published binaries).

**Comment by andriokha** [comment]
Oh wow, thanks, an abundance of options!

> So, if you have SSH keys configured on your account

Ohhhh I can just add SSH keys like normal, what a silly billy, thanks!

And yes you're right, it's not actually blocking SSH per se, it was just preventing the certs being discovered.
