### ISSUE TITLE
Plaform logs command

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#121]
I am not totally sold out on the usefullness of this, but we might want to replicate the "heroku logs" command. Maybe after we get the glorious unified logging... Otherwise this is just running tailf through ssh on app server logs..

This kind of also brings us back to the "plugin" architecture. This is useful to some people.. but will pollute the "platform list" with yet another command, and it is already very dense. Maybe with something like git sub commands

**Comment by pjcdawkins** [comment]
By the way it is now possible to do `platform ssh <command>`, e.g.
```
platform ssh tail -f /var/log/access.log
```

**Comment by pjcdawkins** [comment]
Not quite the same as `heroku logs`, but there is now a `platform logs` command (since v2.12.0)
