### ISSUE TITLE
RFC: What to do about `platform list`?

### ISSUE THREAD

**Issue by Kazanir** [platformsh/platformsh-cli#122]
The `platform list` command is immensely long, to the point of being seriously unwieldly. As we contemplate adding more commands (including toolstack-specific usages) it is worth thinking about how we want to proceed. Some ideas:

- Overwrite the default ListCommand and have it only display root-level commands (not random aliases) and command namespaces, forcing someone to do `platform list namespace` to get each set of subcommands.
- Hook the Toolstack plugin layer to the Application to decide what Toolstack we're in and provide Toolstack-specific commands that way
- Decouple the Application command routing from the commands themselves because that might make this whole process a bit more sane, ala https://www.reddit.com/r/PHP/comments/2hgew0/refactoring_symfonyconsole_to_be_more_reusable/ which Rob linked last week

Specific thoughts are welcome.

**Comment by pjcdawkins** [comment]
Closing this as I implemented option 4, reopen if you think it's still an issue
