### ISSUE TITLE
Build: allow to change the --contrib-destination

### ISSUE THREAD

**Issue by DuaelFr** [platformsh/platformsh-cli#129]
By now, when the "drush make" command is called, the --contrib-destination option is harcoded to the current directory. That might be good for production reasons but during the dev it would be better to be able to build all the contributed projects in the sites/all folder. It would avoid polluting the repository with things that don't need to be there.

I don't know what's the best way to add this to the command line but I think it would only take a few minutes, so I hope you won't wait too long to code it. Alternatively, you can just advice me on how you would see this option and I'll make it.

**Comment by pjcdawkins** [comment]
This is now resolved, which I think is a good thing - Drush Make now runs in the `builds/<build-name>` directory, and repository files are then symlinked individually into the profile (where necessary).

The downside of this is that I've found that PhpStorm may get a little more confused, and there are more symlinks generated.
