### ISSUE TITLE
Make unauthorized error less scary and more helpful

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#14]
I probably had an old invalid token in ~/.platform anyway got a scary red error with no "next steps". deleting the file and logging back worked.
```
Welcome to Commerce Platform!

  [Guzzle\Http\Exception\ClientErrorResponseException]
  Client error response
  [status code] 401
  [reason phrase] Unauthorized
  [url] https://marketplace.commerceguys.com/api/platform/me``à

**Comment by pjcdawkins** [comment]
I haven't ever reproduced this, and anyway there are quite a few changes (including a `logout` command and more detail in exceptions) that may have improved the situation since
