### ISSUE TITLE
Support multiple apps per project

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#159]
And is it documented?

**Comment by OriPekelman** [comment]
Multiple public urls will be left for the moment for the developer to configure .. right ? We don't know what webserver is used. 

We can try and help with a magic nginx conf (and a *.local.platform.sh domain that will always resolve to 127.0.0.1 ) that will set the root dependent on the  host (with project/env/app taken into account) etc.. 

Better probably to leave this to the developer. Its a bit hard to do on our site, and quite easy on hers.

As for drush aliases: Dunno.

**Comment by pjcdawkins** [comment]
Improved in v2.7.0. I'm going to amalgamate various multi-app related issues into a new follow-up.
