### ISSUE TITLE
platform-cli seems to cache project list

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#170]
I created a new project when typing just `platform` I did not see the new project in the list.
When I type `platform projects` the new project appeared
When typing now `platform` I get the correct list

**Comment by pjcdawkins** [comment]
In 1.x and 2.x, the projects list expires after 1 hour, and the environments list after 10 minutes. And it's (still) invalidated if you run `platform projects` or `platform environments`, respectively.

2.x has the potential for proper HTTP caching (it would be a simple config switch), if it is implemented on the API side.

**Comment by OriPekelman** [comment]
Good enough. And as some remember I will be extatic if we set on the API side the etag to the commit hash.
