### ISSUE TITLE
Bug: branches have underscores stripped out

### ISSUE THREAD

**Issue by joshmiller83** [platformsh/platformsh-cli#207]
![image](https://cloud.githubusercontent.com/assets/1440242/5632990/1de2f0b0-95a1-11e4-8173-47fe3da9203f.png)

Not sure if this is an API thing or a CLI thing.

**Comment by pjcdawkins** [comment]
Environments have machine-readable IDs and human-readable names. The IDs can contain letters `a-z`, numbers `0-9` and a `-`.

The CLI tries to deal with this transparently: it does not look for `reg_field_options` because that cannot be an environment ID.

**Comment by joshmiller83** [comment]
![image](https://cloud.githubusercontent.com/assets/1440242/5633394/bc25fb52-95a4-11e4-9993-2cdab41d8a9e.png)

Then I need IDs given to me that don't contain those characters?

**Comment by GuGuss** [comment]
You're right @pjcdawkins, you can't create environments with underscore from the UI, but you can still create a Git branch which have one.

**Comment by damz** [comment]
We don't actually validate the branch names when they are created via Git. We need to fix that.

**Comment by pjcdawkins** [comment]
If these environments were created in @joshmiller83's local Git repository, then the `checkout` command would have simply found the local git branch and checked that out.

I guess this is a fresh clone. Currently the `checkout` command just does `git show-ref refs/heads/<branch>` to find the branch locally - if it checked remote branches too then it might have more chance of succeeding.

**Comment by pjcdawkins** [comment]
I think this would be an appropriate workaround:
https://github.com/pjcdawkins/platformsh-cli/commit/74b97dac176e4c5746535ee613b97c56a1b4ecdb

**Comment by pjcdawkins** [comment]
Fixed in v1.6.2. Thanks @joshmiller83
