### ISSUE TITLE
Not all admin users can create domains

### ISSUE THREAD

**Issue by acrollet** [platformsh/platformsh-cli#234]
Steps to reproduce:

Run the following command as an admin user of a project that did not create the project:

```sh
platform domain:add --project=<ID> <domain name>
```

Expected result:
```sh
Is your domain a wildcard? [y/N] 

The given domain has been successfully added to the project. 
```

Actual result:

```sh
Is your domain a wildcard? [y/N] 


                                                                  
  [Guzzle\Http\Exception\ClientErrorResponseException]            
  The Platform.sh API call failed.                                
  URL: https://eu.platform.sh/api/projects/tcbuhvxlbphsq/domains  
  Error: 403 Forbidden                                            
  Message:                                                        
    Access was denied to this resource.                           
    Unauthorized: collection_create_view failed permission check  
                                                                  


domain:add [--project[="..."]] [--cert="..."] [--key="..."] [--chain="..."] [name]
```

**Comment by pjcdawkins** [comment]
I think there may be confusion between environment-level and project-level permissions here. You need to be be an Admin of the *project* to manage domains.

**Comment by acrollet** [comment]
ok, thanks, that filled in a missing piece - I think it would be very helpful to update the ‘Add user’ link on the environment user management page to say ‘Add user to this environment’ or some such.  

cheers,
Adrian

**Comment by pjcdawkins** [comment]
Yes you are right - plenty of other people have had the same problem.

**Comment by acrollet** [comment]
thanks for the quick response!

**Comment by pjcdawkins** [comment]
This is tracked internally as a Web UI task
