### ISSUE TITLE
Do not ignore all hidden files by default.

### ISSUE THREAD

**Issue by bartfeenstra** [platformsh/platformsh-cli#236]
Ignoring all hidden files by default is a rather radical solution to prevent hidden utility files to be committed accidentally. It can potentially prevent important files such as `.travis.yml` and `.htaccess` from being committed without anyone realizing this until it's too late.

I propose to remove this line from the default `.gitignore` file, or to replace it with more explicit directives.

**Comment by pjcdawkins** [comment]
Thanks - fixed in v1.8.3
