### ISSUE TITLE
Synchronize command should wait for the proper status

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-cli#248]
If there is a Git conflict which results in a failure, the ``sync`` command of the CLI still tells me that: ``The environment has been synchronized.``

**Comment by pjcdawkins** [comment]
Try v 2.x :) which can be released once we have a stable version of the guzzle oauth2 plugin

**Comment by pjcdawkins** [comment]
Meanwhile: https://github.com/platformsh/platformsh-cli/commit/64f7aabd97da6c52dcb67c1d2598fca8c1c0ab65

**Comment by pjcdawkins** [comment]
https://github.com/platformsh/platformsh-cli/commit/4c4f1197d0e31493302f4f72b2970a37522e211e
