### ISSUE TITLE
Launch project:clean with bad keep option value

### ISSUE THREAD

**Issue by GoZOo** [platformsh/platformsh-cli#253]
I call project:clean with keep option in a wrong way : "platform project:clean --keep 1" instead of "platform project:clean --keep=1" or "platform project:clean --k 1".

All build has been deleted, and active build has been deleted to, even without "include-active" option.

I'm wrong, but nothing tell me that this mistake will delete all builds. Shame on me, i have to rebuild my local platform env.

I'm using platform cli 1.8.2.

![capture d ecran 2015-03-13 a 11 10 55](https://cloud.githubusercontent.com/assets/591088/6636736/389647d0-c973-11e4-82ab-177046d116ac.png)

**Comment by pjcdawkins** [comment]
--keep 1 is the same as --keep=1

The clean command has a --max-age option with a default of 86400, so it always deletes builds over 1 day old. The --keep option is also a 'maximum'.

The main problem is it probably didn't detect that your active build was active. I'm investigating that.

**Comment by pjcdawkins** [comment]
The issue was my interpretation of `readlink()`. If you ran `clean` outside the project root, it wouldn't resolve the path of the active build. So https://github.com/platformsh/platformsh-cli/commit/541f60950c1d243a6308c9a9a9490239cb0fbf43 hopefully fixes this.
