### ISSUE TITLE
Trying to install the latest stable version of the CLI using "composer global require 'platformsh/cli:@stable' " command.

### ISSUE THREAD

**Issue by uzair001** [platformsh/platformsh-cli#266]
I am trying to set up local Drupal development. And I am following this document.
To succeed with Platform.sh i need the following installed on my local machine:

I have installed and configure first three things.

id_rsa public/private keypair
Git
Composer
The Platform.sh CLI
Drush

But whenever i try to install "The Platform.sh CLI" , and run run the command composer global require 'platformsh/cli:@stable' i got following error.

linux@ubuntu:~$ composer global require 'platformsh/cli:@stable'
Changed current directory to /home/linux/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - platformsh/cli 1.10.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.0.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.0.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.0.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.0.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.1.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.10.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.10.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.10.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.10.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.5 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.2.6 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.3.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.3.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.4.5 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.5.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.5.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.5.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.5.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.5.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.6.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.6.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.6.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.6.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.7.5 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.4 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.8.5 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.9.0 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.9.1 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.9.2 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - platformsh/cli v1.9.3 requires commerceguys/guzzle-oauth2-plugin ~1.0 -> satisfiable by commerceguys/guzzle-oauth2-plugin[v1.0.0].
    - commerceguys/guzzle-oauth2-plugin v1.0.0 requires guzzle/guzzle >=v3.0 -> satisfiable by guzzle/guzzle[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.1.0, v3.1.1, v3.1.2, v3.2.0, v3.3.0, v3.3.1, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.5.0, v3.6.0, v3.7.0, v3.7.1, v3.7.2, v3.7.3, v3.7.4, v3.8.0, v3.8.1, v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - guzzle/guzzle v3.9.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.9.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.9.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.9.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.8.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.8.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.7.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.6.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.5.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.4.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.3.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.2.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.1.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.7 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.6 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - guzzle/guzzle v3.0.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for platformsh/cli @stable -> satisfiable by platformsh/cli[1.10.3, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.1.0, v1.10.0, v1.10.1, v1.10.2, v1.10.4, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.3.0, v1.3.1, v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.5.0, v1.5.1, v1.5.2, v1.5.3, v1.5.4, v1.6.0, v1.6.1, v1.6.2, v1.6.3, v1.7.0, v1.7.1, v1.7.2, v1.7.3, v1.7.4, v1.7.5, v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.8.4, v1.8.5, v1.9.0, v1.9.1, v1.9.2, v1.9.3].

Installation failed, reverting ./composer.json to its original content.
linux@ubuntu:~$

Can you please tell me where i am going wrong. And how to resolve this issue?

**Comment by pjcdawkins** [comment]
The key error here is: "the requested PHP extension curl is missing from your system"

Since it looks like you're on Ubuntu, you could try:
```
sudo apt-get install php5-curl
```

**Comment by uzair001** [comment]
@pjcdawkins  
Thankyou so much...

**Comment by pjcdawkins** [comment]
You're welcome! I assume it now works for you, so I'll close this issue.

**Comment by spwebguy** [comment]
Thank you very much.
