### ISSUE TITLE
Drupal toolstack hard-coded document root

### ISSUE THREAD

**Issue by petebarnett** [platformsh/platformsh-cli#268]
In a Platform.sh application, the document root can be set in the app config (web.document_root)

For a Drupal application, the build process needs to copy "settings.php" and create some symlinks in "sites/default" within the document root.
The Drupal toolstack however assumes that "sites/default" always exists in the root of the repository, even though this is configurable, and therefore changeable.

I'd like to propose that the CLI should honour the app config, and determine the path to "sites/default" based on this where necessary.

I have implemented the feature locally, and so would be happy to make a pull request after further testing.

**Comment by pjcdawkins** [comment]
Agreed. We should take the opportunity to give builds a proper subdirectory structure and run the same build hooks as on Platform. It's going to make "vanilla" sites more complex though - what should happen there?

IIRC the configured document root is available in LocalBuild::getAppConfig().

BTW if you are making a pull request, note that we are now on version 2.0.0-alpha2 - I reckon there is still the possibility of BC breaking changes, if necessary, before 2.0.0.

**Comment by pjcdawkins** [comment]
I've made a bit of a start in #269, I'm not sure it's the right direction so I'd be interested to see what you did

**Comment by pjcdawkins** [comment]
Committed - https://github.com/platformsh/platformsh-cli/commit/3d1a515e1fb58170339bb18f0e8d139e5b4f297f
