### ISSUE TITLE
Trying to set up my local development environment.

### ISSUE THREAD

**Issue by uzair001** [platformsh/platformsh-cli#271]
Hello
I am trying to set up my local development environment and i am following this [link] (https://docs.platform.sh/use-platform/set-up-local-development/)

But whenever i download a project usning **platform get [project-id] [folder-name]** command.
I got following **sh: 1: drush: not found** error, while i have downloaded drush by **composer global require 'drush/drush:6.*'** command.

**linux@ubuntu:~$ platform get uoml5m5oa72ya my-project
Created project directory: my-project
Enter a number to choose which environment to check out:
  [0] Master
  [1] sprint1
  [2] Test Arif**
 > 
**Enter passphrase for key '/home/linux/.ssh/id_rsa': 
  Cloning into 'my-project/repository'...
Enter passphrase for key '/home/linux/.ssh/id_rsa': 
The project Genero was successfully downloaded to: my-project
Building application php using the toolstack php:drupal
sh: 1: drush: not found
  Changed current directory to /home/linux/.composer
  ./composer.json has been updated
  Loading composer repositories with package information
  Updating dependencies (including require-dev)
  Nothing to install or update
  Generating autoload files
sh: 1: drush: not found
The build failed with an error
 Drush must be installed
linux@ubuntu:~$**

Can anyone please tell me how can i solve this issue?

Thanks.

**Comment by Kazanir** [comment]
This seems to indicate that the Drush "executable" is not in your $PATH. What is the output of `which drush` from your terminal? The CLI instructions normally take care of this by having you add the following to your `~/.bashrc` configuration file or suchlike:

`export PATH="$PATH:$HOME/.composer/vendor/bin"`

**Comment by uzair001** [comment]
Thanks Kazanir ...

**Comment by pjcdawkins** [comment]
Did @Kazanir's answer work for you? (can I close this issue?)

**Comment by alexagui** [comment]
I am running into same issue when trying to install local development on Debian

Drush: 6.40
Platform CLI: 2.0.5

I've updated both `~/.bashrc` and `~/.profile` to have the path to composer/vendor/bin

**Comment by OriPekelman** [comment]
@alexagui can you give us the output of ```which drush```and the precise error message (just to be sure this is the same issue...)

**Comment by alexagui** [comment]
a bit more info for you:
php version PHP 5.4.36-0+deb7u1


`which drush` 
>/home/alexagui/.composer/vendor/bin/drush


output when I run `platform get {id} fi-commerce`

The project FI Commerce was successfully downloaded to: fi_commerce 
Building application php using the toolstack php:drupal 
sh: 1: drush: not found 
Changed current directory to /home/alexagui/.composer 
./composer.json has been updated 
Loading composer repositories with package information 
Updating dependencies (including require-dev) 
Nothing to install or update 
Generating autoload files 
sh: 1: drush: not found 
The build failed with an error 
Drush must be installed

**Comment by pjcdawkins** [comment]
So, somehow, the PHP process isn't getting the same PATH.

You can solve this as a workaround by defining another environment variable in your shell config file:
```
PLATFORMSH_CLI_DRUSH="$HOME/.composer/vendor/bin/drush"
```
(restart shell to continue)

but that really should not be necessary

**Comment by pjcdawkins** [comment]
it's going to be something to do with this: http://stackoverflow.com/questions/3428647/php-exec-path-variable-missing-elements

**Comment by alexagui** [comment]
Hmm no luck.  What's the command that it's trying to run?

What's strange is that I can run `drush` from my command line.
Can I run it manually to get project setup locally?

**Comment by pjcdawkins** [comment]
Really? Can you try this?
```
export PLATFORMSH_CLI_DRUSH="$HOME/.composer/vendor/bin/drush"
platform build
```

You can see the commands it is trying to run with `platform build -v` - but that isn't going to help you much.

**Comment by alexagui** [comment]
Thanks that worked.  

I guess I modified wrong shell config file yesterday since it's basically the same, no?

**Comment by pjcdawkins** [comment]
So, you'd need to add
`PLATFORMSH_CLI_DRUSH="$HOME/.composer/vendor/bin/drush"`
to your shell config file (like `~/.bash_profile`, but ensure it's the right one) - and start a new shell OR type `source ~/.bash_profile` before continuing.

Perhaps you added it to `~/.bash_profile`, but that file is not actually included from your `~/.bashrc`?

**Comment by alexagui** [comment]
Thanks for your help. That worked.

**Comment by pjcdawkins** [comment]
You're welcome. There is a background problem here, so I've added issue 305 ^

**Comment by mtaylor769** [comment]
I realize this thread is almost a year old, but the platform installer adds lines to the .bash_profile, so I added this below it using both techniques from above. Perhaps it can be added to the install script?
```
# Add drush support for Platform.sh CLI
export PLATFORMSH_CLI_DRUSH="$HOME/.composer/vendor/bin/drush"
# Alternatively, uncomment the following line to use drush everywhere:
#export PATH="$PATH:$HOME/.composer/vendor/bin
```
