### ISSUE TITLE
Trying to migrate an existing site to Platform.sh.

### ISSUE THREAD

**Issue by uzair001** [platformsh/platformsh-cli#272]
Hello

I am new to platform.sh and trying to migrate an existing site to Platform.sh and i am following this [link]
(https://docs.platform.sh/toolstacks/php/drupal/migrate-existing-site/)

When i try to push local branch to platform remote using ```git push platform HEAD:master``` command.
I got following error.
```
linux@ubuntu:~/my-project$ git push platform HEAD:master
Enter passphrase for key '/home/linux/.ssh/id_rsa': 
error: src refspec HEAD does not match any.
error: failed to push some refs to 'uoml5m5oa72ya@git.us.platform.sh:uoml5m5oa72ya.git'
```

Can anyone please tell me where i am going wrong and how can i can solve this issue?

Thanks.

**Comment by jmaquet** [comment]
Just if someone faced the same issue, the local repository name must be named "master" as well to avoid this issue.
