### ISSUE TITLE
How to delete Master Environment from platform.sh?

### ISSUE THREAD

**Issue by uzair001** [platformsh/platformsh-cli#273]
Hello

I am new to platform.sh and following this [link] (https://docs.platform.sh/toolstacks/php/drupal/migrate-existing-site/#your-project-doesn-t-use-git-yet)

Now there is also a master available on platform.sh i want to delete/drop that master environment.
How can i do this using **command** line or **platform.sh UI**

Can anyone please tell me how can i do this?

Thanks

**Comment by pjcdawkins** [comment]
Hi @uzair001

You cannot delete the `master` environment on Platform.sh. (I'm not quite sure what you mean by "Now there is also a master available on platform.sh" - what do you need to achieve?)
