### ISSUE TITLE
Token error when access expires

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/platformsh-cli#280]
>```
Client error response [url] https://marketplace.commerceguys.com/oauth2/token [status code] 400 [reason phrase] Bad Request
```

**Comment by anderoy** [comment]
@pjcdawkins What was the solution to this? I am getting a similar message when running platform:
                                                                                                                         
```
[GuzzleHttp\Exception\ClientException]
Client error response [url] https://marketplace.commerceguys.com/oauth2/token [status code] 400 [reason phrase] Bad Request [error] invalid_grant [error_description] Invalid refresh token
```

**Comment by pjcdawkins** [comment]
Hi @anderoy - the solution had many parts, but it was mostly fixed on the server side. For you:

1. Make sure you have the latest version of the CLI with `composer global update` (`2.2.0`, but it reports itself as 2.x-dev ... that will be fixed in the next version).
2. Run `platform login` again

**Comment by anderoy** [comment]
Thanks @pjcdawkins - I had already tried 1. and it didn't work but then after 2. running `platform login` again it worked.

**Comment by pjcdawkins** [comment]
Cool... thanks for your patience!
