### ISSUE TITLE
Unable to install project locally on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexagui** [platformsh/platformsh-cli#281]
I'm not able to install project locally on Ubuntu 14.04
Has anyone also run into this issue?

---
$ platform --version
Platform.sh CLI version 1.10.7

---

Enter a number to choose which environment to check out: 
[0] Master 
[1] Staging 
> 1 
The authenticity of host 'git.us.platform.sh (54.210.55.162)' can't be established. 
RSA key fingerprint is 22:xx.yy
Are you sure you want to continue connecting (yes/no)? yes 
`Failed to connect to the Platform.sh Git server` 
Please check your SSH credentials or contact Platform.sh support

**Comment by pjcdawkins** [comment]
Hi Alex

Could you try SSH with `-v` to see if there is a problem with your key?
```
ssh -v <project>-master@ssh.us.platform.sh
```

If that doesn't reveal the issue, please open a support ticket at https://marketplace.commerceguys.com/platform/support/create to continue (it seems the problem is specific to your account, not the CLI).

**Comment by alexagui** [comment]
Thanks @pjcdawkins for the quick response.

Indeed I didn't have the correct key loaded in my ssh agent.

**Comment by amine-betari** [comment]
Hi @pjcdawkins 
 I have this response 
no matching cipher found: client aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour,aes192-cbc,aes256-cbc,rijndael-cbc@lysator.liu.se server aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
debug1: Calling cleanup 0x419f10(0x0)

Do you habe any idea  ?

**Comment by pjcdawkins** [comment]
@amine-betari this would be very dependent on your own system configuration.

What's your SSH version (`ssh -V`)?

For what it's worth, my Mac (`OpenSSH_7.6p1, LibreSSL 2.6.2`) selects the `aes128-ctr` cipher:

```
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256-etm@openssh.com compression: none
```
