### ISSUE TITLE
Detect does not seem to run on  toolstack php:symfony

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#289]
Even if there is no "composer.json" file it seems to get detected..  followed by an error message.
(Platform.sh CLI version 2.0.2)

Building application php using the toolstack php:symfony
Found a composer.json file; installing dependencies
  Composer could not find a composer.json file in.....

**Comment by pjcdawkins** [comment]
Thanks - fixed, and I'll be tagging a release soon
