### ISSUE TITLE
Github integration with repositories with a . in title does not work

### ISSUE THREAD

**Issue by istos** [platformsh/platformsh-cli#314]
If a github repo has a . in its name the Github integration will not work. Haven't looked into the platform.cli code but probably a simple parsing issue?

Error message receive is:
The option "repository" with value "roomify/roomify.us" is invalid.

**Comment by pjcdawkins** [comment]
Hi Ronald - this was fixed in v2.1.0: https://github.com/platformsh/platformsh-cli/commit/c1259bbd45caf2e9d921e950287b61eaa23f2ff3

**Comment by istos** [comment]
Awesome - thanks!
