### ISSUE TITLE
Shell configuration file not reloeaded automatically

### ISSUE THREAD

**Issue by SirTadpole** [platformsh/platformsh-cli#318]
Hello,

After installing platformsh-cli on my lxc-container, i added this line on my shell configuration file : 

```
export PATH="$PATH:$HOME/.composer/vendor/bin"
. "$HOME/.composer/vendor/platformsh/cli/platform.rc" 2>/dev/null
```

When i load manually "source ~/.bashrc", all is OK, i can run platform commands. 
But if i start a new shell (and after connecting my LXC-container of course), platform commands are not recognized.
I have to run "source ~/.bashrc" manually, before using platform.

Any help is welcome.

**Comment by pjcdawkins** [comment]
The `~/.bashrc` is inside the container, I guess? How are you connecting to the container?

**Comment by SirTadpole** [comment]
Yes, the *~/.bashrc* is inside the container and I'm connected with ssh. (ssh -A {user}@{container}.lxc)

**Comment by ralt** [comment]
Can you run `cat /etc/passwd | grep $USER | awk -F':' '{ print $7; }'` and paste the output, in the container?

**Comment by SirTadpole** [comment]
> domeo:/etc/apache2/sites-enabled# cat /etc/passwd | grep $USER | awk -F':' '{ print $7; }'
> /bin/bash

**Comment by SirTadpole** [comment]
Problem solved by modifiying ~/.profile with : 

    if [ -n "$BASH_VERSION" ]; then
        # include .bashrc if it exists
        if [ -f "$HOME/.bashrc" ]; then
            . "$HOME/.bashrc"
        fi
    fi
