### ISSUE TITLE
Support SSH in multi-app

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-cli#326]
When running ``platform ssh`` nothing happens, whereas running ``platform ssh -v``, I got the available methods.

That'd be great if the CLI would automatically propose the available options.

![multi-app SSH command](https://cloud.githubusercontent.com/assets/1927538/9229939/d9cfd89a-411f-11e5-97a3-efc26443d927.png)

**Comment by pjcdawkins** [comment]
We'd need an API to find this information

**Comment by OriPekelman** [comment]
see https://platformsh.atlassian.net/browse/PF-4 (internal)

**Comment by pjcdawkins** [comment]
Improved in v2.7.0. I'm going to amalgamate various multi-app related issues into a new follow-up.
