### ISSUE TITLE
Unclear error message: Unauthorized: collection_create_view failed permission check

### ISSUE THREAD

**Issue by ralt** [platformsh/platformsh-cli#327]
This happens when doing an admin action on a project where you only have viewer permissions, e.g. adding an integration.

**Comment by pjcdawkins** [comment]
At least partially addressed by: https://github.com/platformsh/platformsh-cli/commit/66f923c9d9c54ff7066cc12e2ac05b70eeeee54a#diff-786a7f978fea207b90b7f83b73432b8d
