### ISSUE TITLE
Feature Request: Drush Aliases use Project Folder name when "getting"

### ISSUE THREAD

**Issue by joshmiller83** [platformsh/platformsh-cli#330]
If I run

    $ platform get 3eelsfv6koejw lp

And then I 

    $ cd lp

And run

    $ platform drush-aliases

I would love to see

    @lp.master
    @lp.develop

Instead I see

    @3eelsfv6koejw.master
    @3eelsfv6koejw.develop

**Comment by pjcdawkins** [comment]
This was mentioned before so I finally implemented it v2.4.0. So update to the latest version v2.4.3 and it should work for you - re-open this if not!
