### ISSUE TITLE
add/modify role for environment

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#333]
There might be a discrepancy in the CLI as it seems we can not change environment role only project level roles (as command line option).

**Comment by pjcdawkins** [comment]
Au contraire

```
 Give Alice the 'contributor' role on the environment 'test':
   platform user:role alice@example.com --level environment --environment test --role contributor
```

**Comment by OriPekelman** [comment]
Stupidly enough I looked at the  platform user:add instead of user:role
