### ISSUE TITLE
platform environment:deactivate

### ISSUE THREAD

**Issue by vincenzo** [platformsh/platformsh-cli#357]
Hi, 

It'd be good to have a new command `platform environment:deactivate` or simply add an option to `environment:delete` command that assumes a `n` as the answer to the second question asked by the delete command. I am basically looking for a way to the following, but in one command without questions being asked. I can't use the `-y` switch in this case, because I want my answer to the second question to be 'no'.

```
platform environment:delete -p ewaqe3q24324 -e test1           
The environment test1 is currently active: deleting it will delete all associated data.
Are you sure you want to delete the environment test1? [Y/n] 
Delete the remote Git branch too? [Y/n] n
```

**Comment by pjcdawkins** [comment]
#361 has been merged, so that fix is available in the `dev-development` version. I'll tag a stable release in the next couple of days.

**Comment by vincenzo** [comment]
My pleasure. You're gonna get more from me. Got a few things to work on.

**Comment by vincenzo** [comment]
:+1:
