### ISSUE TITLE
Integrations, repositories, local deployment

### ISSUE THREAD

**Issue by vincenzo** [platformsh/platformsh-cli#366]
Hi, 

I've been advised to talk about this here. Please tell me if this is the wrong place and I should instead open a support ticket with platform.sh.

So...

I am trying to solve a problem and I am hoping that part of my solution is going to be useful to the general public and if so, I'll contribute it to the CLI project.

As I understand, having things like a Github integration or a Bitbucket one will not "disable" (somehow) the p.sh repository associated with the project. In fact, I am inclined to think I could have different code in both and branch off both and still get a p.sh an environment associated with both those branches? I haven't actually tested this, but the way things are done lead me to think that's the case. 

Also, part of the issue is that I can have multiple integrations active, like both a Github and a Bitbucket one. Now, I understand integrations are not there to just integrate with external Git repositories (I can see Blackfire and HipChat in there).

The more general issue I have is this though: I need to be able to tie one particular git repository with the project exclusively. That is, if I have Github backing my project, I don't want any other Git repo active for the project. 

As part of this, I'd expect the CLI to be able to know about which repo is active and pull, branch, etc. using that repo. I was working on a pull request for this, when I realised the issues listed above. 

Another way I see this working is if the integration would work to keep the repos in sync. So it's always the p.sh repo to power the project, but the integration with Github for example will keep the repos in sync. E.g., when I merge a pull request from a branch to, say, the qa branch, the related qa branch on the p.sh repo is updated accordingly. This could be extended to keep in sync all the 'Git' integrations, but I realise there might technical limitations that I am unaware of that could prevent this. 

Let me know if any discussion can happen around this. 
Meanwhile, I’ll work towards a temporary solution.

PS: the options `--build-pull-requests` and  `--fetch-branches` don't seem to work properly. According to the doc, I can pass `true` or `false` to those. I passed `false` to both and yet both were treated as if `true` was passed to them. Let me know if you want me to record this issue here in the "PS" in its own Github issue.

**Comment by pjcdawkins** [comment]
> Another way I see this working is if the integration would work to keep the repos in sync

It does, pretty much. Our GitHub and Bitbucket integrations respond to events sent by those respective services, and then they make the Platform.sh repo match what's in the user's GitHub/Bitbucket repo. The synchronization only goes one way. You are expected to work exclusively with the GitHub / Bitbucket repository from then on, which has these implications:

* the Platform.sh "Merge" button/command becomes pretty much useless
* the Platform.sh "Branch" button/command might be useful for determining the correct 'parent' of a new branch, but other than that edge case, it's useless
* the "Routes" administration in the Platform.sh web UI becomes more or less useless, because it commits to your repository, and the next time we sync from GitHub / Bitbucket, those commits would be wiped out
* you should set your main Git remote in your repository to GitHub / Bitbucket, and push to those instead of Platform.sh

**Comment by pjcdawkins** [comment]
> According to the doc, I can pass `true` or `false` to those. I passed `false` to both and yet both were treated as if `true` was passed to them

I'm not sure about that, I've tested and it seems `false` is treated properly. The code that converts your input into a real Boolean is here: https://github.com/platformsh/console-form/blob/master/src/Field/BooleanField.php#L25-L27

**Comment by vincenzo** [comment]
Ha, thanks @pjcdawkins. I probably assumed too much there, so I am glad to see that most of what I need is there and I am sorry for keeping you busy telling me things I could've found out myself. 

I had started working on a pull request to make the `Platformsh\Client\Model\Project::getGitUrl()` method aware of the integrations and return the right repo. However, when I realised that you can have multiple integrations active at the same time (you can, can't you?), I stopped. 

Do you think it's worth to work out a solution for that?  

Or shall I just come up with a solution for my specific case (I have a local deployment built around platform CLI) and basically modify the remotes of the repo if a Github integration (the only one we'll be using) is present?

**Comment by vincenzo** [comment]
Re those switches, I'll test again, but so far it did the same thing twice for me.

**Comment by vincenzo** [comment]
@pjcdawkins One quick question about this if you don't mind: does the `integrations` API require admin permissions for the user invoking it?

**Comment by pjcdawkins** [comment]
@vincenzo yes, you need to be an admin to do anything with a project's integrations
