### ISSUE TITLE
`drush @pid.branch ssh` should have the --cd equal the .platform.app.yaml web:document_root

### ISSUE THREAD

**Issue by joshmiller83** [platformsh/platformsh-cli#370]
When using platform to run drupal inside of a folder (as is the case for sites originally hosted on Acquia) an you try to ssh into the environment using the site alias, it wrongly passes "/app/public" and the ssh connection is refused. If we are passing a "cd" then it should equal the one defined in the .platform.app.yaml as the document root.

![image](https://cloud.githubusercontent.com/assets/1440242/11005817/2658fe60-848e-11e5-8169-217cef2efacf.png)

**Comment by pjcdawkins** [comment]
The trouble is, that as well as the code complexity of checking your local .platform.app.yaml files for the document_root of each application, your local repository isn't a guarantee of what the remote environment contains - guessing that the document_root matches up on both is also flawed.

But this could still be implemented.

**Comment by pjcdawkins** [comment]
The PR really does show the complexity ("10 changed files with 343 additions and 147 deletions") and it's still no guarantee that the remote root will be correct, but it might be good enough

**Comment by damz** [comment]
On the other hand, it doesn't make sense to generate the remote aliases from the local app config, no? The config can and will be different depending on the environment.

**Comment by pjcdawkins** [comment]
That could be the user's problem for now, until we have an API to find the real config for each app (per env)

**Comment by damz** [comment]
@pjcdawkins In that case that sounds like a big change with little gain, no? Or is the architecture reusable later?

**Comment by pjcdawkins** [comment]
Yes it's a big change, although the code gets a little bit refactored so the additions are not all bad. The gain depends on how long it would last as a stop-gap, before we implement an apps API. The code is not exactly reusable but yes the general ideas are there (and all that remains is to swap the information source, from local config to remote API).

**Comment by pjcdawkins** [comment]
Improved in v2.7.0. I'm going to amalgamate various multi-app related issues into a new follow-up.
