### ISSUE TITLE
Local build and relative paths

### ISSUE THREAD

**Issue by mitrpaka** [platformsh/platformsh-cli#374]
Prior to 2.6.3 version build command used relative paths as a default when symlinks were used.

From 2.6.3 onwards this seems to be broken as all symlinks are using absolute paths (even when _not_ using -a option)

Platform.sh CLI version 2.6.3
Pasis-MacBook-Pro:aspa mitrpaka$ ls -la www/sites/default/
total 120
...
default.settings.php
files -> /Users/xxx/Dev/platform.sh/aspa/shared/files
libraries -> /Users/xxx/Dev/platform.sh/aspa/repository/libraries
modules -> /Users/xxx/Dev/platform.sh/aspa/repository/modules
settings.local.php -> /Users/xxx/Dev/platform.sh/aspa/shared/settings.local.php
settings.php
themes -> /Users/xxx/Dev/platform.sh/aspa/repository/themes

**Comment by ralt** [comment]
The relevant commit seems to be this one: https://github.com/platformsh/platformsh-cli/commit/db30314da228143256cc822511e8eb3e6676ea6a#diff-78c8914bf355cb6fccb9f2d52f1d6171R242

**Comment by pjcdawkins** [comment]
I think the problem I was trying to avert was that if you try to move a file from sites/default in your build hook, and it was actually a symlink locally, you'd end up with a broken relative link. But that was not really the right fix.

**Comment by vincenzo** [comment]
Hi @pjcdawkins - Are you going to create a release with this change in any time soon? 
That kinda broke our setup here where I work :) (I have the build dir shared via SSHFS mount from guest to a host machine, and absolute paths don't play well with that).

**Comment by pjcdawkins** [comment]
@vincenzo this is now in v2.7.1

**Comment by vincenzo** [comment]
Thanks @pjcdawkins
