### ISSUE TITLE
[Exception]  Unexpected output from command 'drush --version'

### ISSUE THREAD

**Issue by sirtet** [platformsh/platformsh-cli#376]
While (or after? the output is not clear about that)
doing `platform get [id]`
I got an error about my drush version.

>   Cloning into '/home/drupalpro/websites/kanuschule/repository'...
>
> The project kanuschule.ch was successfully downloaded to: kanuschule
>                                                      
>   [Exception]                                         
>   Unexpected output from command 'drush --version':   
>   drush version 5.8                                   
>                                                      
> project:get [-e|--environment ENVIRONMENT] [--no-build] [--host HOST] [--] [<id>] [<directory>]

Telling the expected output (minimum version?) would be what i expected ;-) 
Maybe it should also say if this was an error *during* the _get_ command, or if this is just concerning the future use of drush.

**Comment by pjcdawkins** [comment]
Hi @sirtet - agreed it should not have failed completely with this - the above commit fixes it.

You can fix your own issue by upgrading Drush to version 6 or above (I'd recommend 7.1.0, if you aren't using Drupal 8).
