### ISSUE TITLE
Don't symlink builds directory in out of platform build

### ISSUE THREAD

**Issue by dwkitchen** [platformsh/platformsh-cli#408]
When running `platform build` for a cloned repository (from BitBucket or Git for example) rather than using platform get; the builds directory is also symlinked in to the `sites/default` folder.

This shouldn't happen, this is also the same if the destination directory is inside the source.

**Comment by pjcdawkins** [comment]
Thanks, it should be fixed with those commits ^ to be released soonish.

The restructure in #406 would make this sort of thing simpler.
