### ISSUE TITLE
Parameters don't seem to be respected when creating a GitHub integration

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-cli#409]
I ran the following command to enable the GitHub integration:
```
augustin ~/projects/platform-projects/aaa/bbb platform integration:add --type=github --project=d4tobd5qpizwa --token=xxx --repository=aaa/bbb --build-pull-requests=true --fetch-branches=false
```

It worked fine but still tracks PRs:
```
Created integration yyy (type: github)
Repository: aaa/bbb
Build PRs: yes
Fetch branches: yes
Payload URL: https://eu.platform.sh/api/projects/d4tobd5qpizwa/integrations/yyy/hook
```

Updating the integration to not track PRs worked fine.

**Comment by pjcdawkins** [comment]
I don't know how I ever thought that could work... fixed in v2.11.1 via https://github.com/platformsh/console-form/commit/420f72e2f0c30f06dee2a503234aa066214cdb22
