### ISSUE TITLE
Default Helpers have no output

### ISSUE THREAD

**Issue by vincenzo** [platformsh/platformsh-cli#412]
I am sure [this is no news](https://github.com/platformsh/platformsh-cli/blob/development/src/Application.php#L63-L73) to you, @pjcdawkins. 

This affects the debug output too, though. For example, execution of drush commands via the default drush helper with a higher verbosity level will not result in the debug to be printed out on the screen, because the ShellHelper instantiated in the DrushHelper constructor takes the same output as the DrushHelper, which is null.

Is this ok? 

As you might know by now, I maintain an extended version of the CLI, hence why I encountered this issue. I easily worked around it by instantiating a new DrushHelper, but I thought I'd bring the whole matter to your attention, just in case...

**Comment by pjcdawkins** [comment]
The whole Helper thing is a bit silly, yes, and I'd like to find a better alternative.

**Comment by vincenzo** [comment]
I'll tell you my personal view: I don't think there should be a helper set at all. I think it's more appropriate to instantiate helpers as one needs. My 2c.

**Comment by pjcdawkins** [comment]
They all have the same output object now, if instantiated via the `CommandBase->getHelper()` method - since v3.0.1.
