### ISSUE TITLE
environment:sql-dump --file option help is misleading

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-cli#417]
`platform help sql-dump` says:

```  -f, --file=FILE                A filename where the dump should be saved. Defaults to "environment-dump.sql" in the project root```

If you omit the `--file` option, the file won't actually be called `environment-dump.sql`. It'll be called `master-dump.sql`, or whatever.

Can we clarify this somehow? Not sure exactly how to phrase it....

**Comment by fuzzbomb** [comment]
how about:

A filename where the dump should be saved. If omitted, it will be saved in the project root with a filename which includes the environment name, like <environment>-dump.sql

**Comment by pjcdawkins** [comment]
Fixed in [v2.13.0](https://github.com/platformsh/platformsh-cli/releases/tag/v2.13.0)
