### ISSUE TITLE
Add timestamp option in sql-dump command

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-cli#419]
It would be nice if we could get a timestamp in the sql-dump without having to type it manually with the --filename option.
 
Can we have a `-t, --timestamp` option?
I suggest a 24-hour format, and avoid timezone amibguity by using UTC explicitly.

Other things to consider:
- Where would the timestamp com in relation to the filename and file extension? e.g. `master-dump.20160218-161523+0000.sql` inserts a timestamp  after the filename, but before the extension.
- How would it play with the --filename option?

**Comment by pjcdawkins** [comment]
Creating the timestamp would work but it is a little ugly (I [experimented a bit](https://github.com/platformsh/platformsh-cli/commit/235805763717da32d7773961beb3b12b2e108c7a)).

Is there a standard timestamp format that is machine-readable, human-readable, *and* valid in a filename on Windows + Linux? None of these options fit the bill:

 * Unix timestamp (not human-readable)
 * ISO 8601 e.g. `2004-02-12T15:19:21+00:00` (contains `:` so not valid on Windows)
 * RFC 2822 e.g. `Thu, 21 Dec 2000 16:01:07 +0200` (also contains `:` and very long)
 * Something custom like your `20160218-161523+0000` or my `2016-02-22_19-51-24_0000` (can't be read by PHP's `strtotime()`)

**Comment by ralt** [comment]
Something custom can easily be read by `DateTime::createFromFormat` though, so I'd just rely on being human readable and unambiguous.

**Comment by pjcdawkins** [comment]
OK, I've added that to PR #423 with this kind of timestamp: `20160223-121223-0000`

**Comment by pjcdawkins** [comment]
Added in [v2.13.0](https://github.com/platformsh/platformsh-cli/releases/tag/v2.13.0)
