### ISSUE TITLE
Update to version 2.13.0

### ISSUE THREAD

**Issue by tschet** [platformsh/platformsh-cli#425]
When I updated to version 2.13.0 today it seems to have broke something. Platform get works, but platform build no longer works. It crashes part way through the drush make process.
[Exception]
  The command failed with the exit code: 1
  Full command: '/usr/local/bin/drush' 'make' '/Users/username/Sites/project/repository/project.make' '/Users/username/Sites/project/bu
  ilds/2016-02-26--13-20-46--master/public' '--yes' '--cache-duration-releasexml=300' '--concurrency=4'

It's also generating errors related to symfony
[Symfony\Component\Console\Exception\CommandNotFoundException]

**Comment by tschet** [comment]
On further review, the problem seems dependent on my project.make file rather than the update. The .make file works on platform.sh, but crashes the cli tool on local "platform build" commands. If I comment out most of the modules in the make file, it works.

**Comment by tschet** [comment]
After several hours of downtime, I've identified the problem, and it isn't the CLI tool. I was hitting a Drush memory limit during the site build. I hadn't seen the errors before, but they were repeatable by using Drush "make" directly on the project.make file.

**Comment by pjcdawkins** [comment]
Thanks for noting that you solved this yourself - I'll close the issue
