### ISSUE TITLE
help for environment:merge is vague

### ISSUE THREAD

**Issue by fuzzbomb** [platformsh/platformsh-cli#428]
Following on from #421, the merge command also has vague help.
- "merge" sounds similar to "sync" - are these operations related at all? If so, what's the difference?
- "merge" is a git term, sync isn't. Is environment:merge about merging code? The help doesn't mention code, branches, tags or other git refs.
- The example talks about a "parent" but doesn't elaborate. What does parent refer to?
- Does this move anything to/from my development laptop?
- Do databases change as a result of this command?

I haven't dared to run environment:merge or environment:sync yet!

**Comment by pjcdawkins** [comment]
This commit is in version 2.13.1, by the way:
https://github.com/platformsh/platformsh-cli/commit/d3118dc3e2c509378d1c6bd6bb037b7d9a929ef9
