### ISSUE TITLE
How are you supposed to login to the cli if you chose to use google login when doing the trial?

### ISSUE THREAD

**Issue by testjohn1234** [platformsh/platformsh-cli#432]

**Comment by pjcdawkins** [comment]
You can set a password in your account: https://accounts.platform.sh/user/password

**Comment by pjcdawkins** [comment]
I've added that to the `platform help login` output (in commit https://github.com/platformsh/platformsh-cli/commit/ffc333c53dc3319d42eea0518bd0e98ff727dc54)
