### ISSUE TITLE
PDOException Drush 8.1.2

### ISSUE THREAD

**Issue by AndyLicht** [platformsh/platformsh-cli#466]
I´ve installed Drush 8.1.2 on Ubuntu 14.04(php 5.5.9) with composer.
When i am using drush outside of a drupal directory, everything works fine, i am getting:
 PHP executable         :  /usr/bin/php
 PHP configuration      :  /etc/php5/cli/php.ini
 PHP OS                 :  Linux
 Drush script           :  /root/.composer/vendor/drush/drush/drush.php
 Drush version          :  8.1.2
 Drush temp directory   :  /tmp
 Drush configuration    :
 Drush alias files      :

When i am using drush inside a drupal 8.1.1 project, i am getting this error:
/var/www/drupal# drush status
PDOException: could not find driver in /var/www/drupal/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79
Drush command terminated abnormally due to an unrecoverable error.                                                 [error]
PDOException: could not find driver in Drupal\Component\DependencyInjection\PhpArrayContainer->createService() (line 79 of /var/www/drupal/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php)

SO maybe this is a bug.
Thanks for helping me.
Andy

**Comment by pjcdawkins** [comment]
Hi Andy, what's in your Drupal `$databases` configuration? (find it in `settings.php` or `settings.local.php`)

I think usually you'll get this error if that configuration is incorrect or incomplete

**Comment by AndyLicht** [comment]
Sorry, i´ve reinstalled everything, and now it works fine
