### ISSUE TITLE
Windows issue with Drush installed

### ISSUE THREAD

**Issue by mallenuk** [platformsh/platformsh-cli#477]
On version 3.3.0 and upwards any command that requires Drush fails to run with a DependancyMissingException error. Drush is correctly installed and can be run from the command line but Platform.sh cli complains that Drush is not installed when attempting to run drush.bat.

**Comment by pjcdawkins** [comment]
Does the error message state the `command attempted:` at the end? What's the result of the command `where drush`?

Meanwhile, there is a workaround for this: edit the `.platformsh\config.yaml` file (in your home directory) and add the lines:

```yaml
local:
  drush: /path/to/drush
```

**Comment by mallenuk** [comment]
"where drush" returns the paths. But "where C:\Users\mallen.UK\AppData\Roaming\Composer\vendor\bin\drush.bat" returns "ERROR: Invalid pattern is specified in "path:pattern"". If I use 3.2.2 I don't get this error and builds work fine.

**Comment by mallenuk** [comment]
I have tried the workaround as well and the same issue comes up.
