### ISSUE TITLE
Arguments not being parsed properly

### ISSUE THREAD

**Issue by TLyngeJ** [platformsh/platformsh-cli#486]
It looks like, at least some of, the arguments doesn't get parsed properly when using `platform drush`

I usually use `platform drush sql-dump --gzip`, but when I updated the CLI this morning, to version 3.3.5, I didn't get the gzipped version of the DB, but the raw text version.

Downgraded to version 3.3.4 and it started working again.

**Comment by ralt** [comment]
This is because of this PR: https://github.com/platformsh/platformsh-cli/pull/485

To immediately fix it, you can quote the arguments. I'm not sure what @pjcdawkins plans on doing for this behavior though, since it's quite handy.

**Comment by pjcdawkins** [comment]
Yes, quote it as @ralt says:
```sh
platform drush 'sql-dump --gzip'
```

By the way, an alternative (Drush/Drupal agnostic) would be:
```
platform sql-dump --stdout | gzip
```

I don't think it's worthwhile to restore the unquoted syntax, I'm not sure if it has any advantages, beyond sugar? It involved a lot of code and it was causing an infinite recursion bug, in a parsing method copied from Symfony Console, which I couldn't explain.

**Comment by ralt** [comment]
Just sugar, being able to copy paste drush commands and prepending `platform`.

Your call.

**Comment by pjcdawkins** [comment]
Ah actually, there is still a bug, in that it's not properly validating input so it just drops the extra arguments silently...

**Comment by TLyngeJ** [comment]
Looks good. Thanks guys!
