### ISSUE TITLE
is there a way to prevent backing up local builds?

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-cli#503]
Looking at the code I didn't find a one.

**Comment by pjcdawkins** [comment]
Would you like one? 😃  See the pull request linked above.

**Comment by hanoii** [comment]
And regardless of the follow up on the PR, awesome, thanks!

**Comment by pjcdawkins** [comment]
Added in [v3.5.0](https://github.com/platformsh/platformsh-cli/releases/v3.5.0)
