### ISSUE TITLE
If we use github integration, we have to define --project & --environment

### ISSUE THREAD

**Issue by benftwc** [platformsh/platformsh-cli#506]
Hello,

After migrate from platform's git to github's one, I can't use CLI commands if I don't specify project and/or environment (depends on command typed)

Exemple : 
`$ platform ssh` won't work if Github integration is enabled, you'll should use `--project="xx" --environment="develop"` instead.

**Comment by benftwc** [comment]
In addition, seems any other complex commands need to be quoted to work, like `platform --project='xxxx' --environment='develop' drush 'ev "custom_php_function(\'param1\', \'param2\');"'`, which is just impossible to use through Unix alias system

**Comment by pjcdawkins** [comment]
Re. your first comment, the "project root" directory is detected from:

1. The file `.platform/local/project.yaml` (the CLI searches recursively upwards through the directory tree, looking for this filename)
2. The `platform` or `origin` Git remotes, if the current directory is within a Git repository, and if one of those Git remotes has a URL containing `platform.sh`

If within a "project root", then you don't need to specify `--project`, and you usually don't need to specify `--environment`.

So, you can fix this (your first comment) by running:

```sh
git_url=$(platform project:info --project="xxx" repository.url)
git remote add platform "$git_url"
```

**Comment by TomOA** [comment]
I think it would be nice to have a `platform project:set` command to create the `project.yaml` and `platform` git remote for us.  If you would combine that with the `--title` option from the `platform project:list` command it could be very helpful (for me).  So it would be like `platform project:set --title MyProject` and "bam!" your repository is linked to your platform.sh project.

**Comment by pjcdawkins** [comment]
There's now (since version 3.12.0 a couple of weeks ago) a command:
```
platform project:set-remote <id>
```
which adds the `platform` Git remote and the `.platform/local/project.yaml` file.
