### ISSUE TITLE
Running platform-cli from a php container, setting a home directory?

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-cli#515]
Hi, this is just a follow up from 

https://platformsh.zendesk.com/requests/10260

I wanted to configure a cron that triggers a snapshot from within the php container and I think I have it working by tweaking a few things on your suggestions (which were great btw, thanks).

One issue I found is that I needed to download the phar to /tmp so that it is writable, otherwise it complained, but then was also getting:

```
  [InvalidArgumentException]
  The directory "/app/.platformsh/cache" does not exist and could not be created.
```

I tried configuring a config.yaml file in /tmp with 

```
application:
    user_config_dir: './'
```

But that didn't work either, and looking at the code it seems the client search for the config.yaml where it is executed, but then apparently not.

I ended up adding a .platformsh mount in .platform.app.yml

```
mounts:
    "/.platformsh": "shared:files/.platformsh"
```

Which worked fine, but just wondering if I could have done all this on /tmp and not use the mount.

**Comment by pjcdawkins** [comment]
It looks for that `config.yaml` within itself - within the Phar archive - which is what that CLI_ROOT constant means (it would be something like `phar://home/username/.platformsh/bin/platform`).

There is another workaround. Both the CLI and the installer use `HOME` to determine the home directory. So, if you can run the CLI and the installer prefixed with `HOME=/tmp`, then the config dir will end up in `/tmp/.platformsh`.

**Comment by pjcdawkins** [comment]
The CLI now uses `/tmp` (well, the PHP system temp dir) for the cache and other temporary files, if `$HOME/.platformsh` is not writable.
