### ISSUE TITLE
brew formulae for macOS

### ISSUE THREAD

**Issue by wingsuitist** [platformsh/platformsh-cli#528]
Create brew formulae for installing it on macOS using http://brew.sh/

**Comment by pjcdawkins** [comment]
Is the installer not suitable?
```
curl -sS https://platform.sh/cli/installer | php
```

Generally, because this runs as just a single Phar (effectively just a PHP script), I want to keep the install as simple and generic as possible.

**Comment by OriPekelman** [comment]
Also brew really dislikes auto-updating software. Which the CLI does. So you would want to turn-off autoupdating.. which sounds bad.

**Comment by ralt** [comment]
How does composer itself do? Is it even on brew?

**Comment by pjcdawkins** [comment]
There are brew formulae, apt packages,  etc. for Composer, but the more convenient way to install Composer is directly from their Phar, which can auto-update, etc. So I feel the other methods aren't useful.

**Comment by wingsuitist** [comment]
Thank you very much for your feedback, I absolutely understand your point. There is a big PHP brew package repository, but it's true that managing composer and it's packages with brew isn't the best thing. It's like installing node.js with brew :-), it's fun at first, but after a while you update and do stuff and then it starts to break...
