### ISSUE TITLE
platform sql dump questions

### ISSUE THREAD

**Issue by webprogrammierer** [platformsh/platformsh-cli#538]
Hello,

I have a huge database and have some question about the best way to work with it:

`platform db:dump` dumps the database to my local computer in sql-format. 
Is there a way to select the branch from which the dump should be done?
Are there any options for `platform db:dump`?

I found this command:
`platform environment:sql-dump -e stage`
Is this the better way to make sql-dumps?

How can I use the platform command to dump the database in gzip format?

If the databse is very huge: What is the best way to dump the database file to my local computer in order to import it in my local dev envirenment (cloned from platform.sh)?

And what is the best way to import the dump files (local dev envirenment).

Are there other ways to get or synch huge databases from platform.sh (stage or master branch) to my local dev environment?

Thank you very much.

**Comment by pjcdawkins** [comment]
`db:dump` and `environment:sql-dump` are the same thing.

You can select the branch for _any_ relevant CLI command with the `--environment` (`-e`) option. By default it uses the currently selected branch in Git (if available). You can also specify the project with the `--project` (`p`) option.

Run `platform db:dump -h` or `platform help db:dump` to see all the available options (this works for any command).

The `db:dump` command will stream the database over SSH - it simply runs the `mysqldump` or `pg_dump` command over SSH - and gives you the output. This can work for large databases too, although the efficiency depends on the network speed. The SSH connection itself is compressed.

By default the `db:dump` command will create a file. But you can use the `--stdout` option to output to stdout, which means you can pipe to other commands, e.g. you can create a gzipped file with:
```sh
platform db:dump --stdout | gzip > ./my-dump.sql.gz
```

There are other ways to get or sync huge databases, yes. You can SSH to the environment and create a temporary dump file on the environment itself, for example (over SSH):

```
mysqldump --no-autocommit --single-transaction --opt -Q main --host=database.internal --port=3306 --user=user --password= | gzip > /tmp/temporary-dump.sql.gz
```

N.B. watch out that the `/tmp` volume only has about 1GB available. You could create a file mount if you need more space.

You can then rsync the file from the environment to your local:

```
export SSH_URL=$(platform ssh --pipe)
rsync -v "$SSH_URL":/tmp/temporary-dump.sql.gz temporary-dump.sql.gz
```

(note the first line gets the SSH URL from the CLI - you might want to add the `--environment` or `-e` option there too)

**Comment by webprogrammierer** [comment]
Thank you for the detailed answer.

Is
`platform db:dump --stdout | gzip > ./my-dump.sql.gz`
faster then
`platform db:dump` ?

And how can I import the zipped sql file "my-dump.sql.gz" into my database on localhost?

**Comment by pjcdawkins** [comment]
The first command isn't faster, but it will produce a smaller file.

To import a gzipped file, either:

* Expand it into a normal SQL file first, then import it:

  ```sh
  gunzip my-dump.sql.gz # this creates my-dump.sql
  mysql -h localhost -u someuser -D somedatabase -p < my-dump.sql
  ```

* Decompress it to stdout (using `gunzip -c` or `zcat`) piping the result into mysql directly. This uses less disk space because it avoids creating an intermediate file, but it's harder to inspect the SQL if there's an error. Example:

  ```sh
  gunzip -c my-dump.sql.gz | mysql -h localhost -u someuser -D somedatabase -p
  ```

**Comment by webprogrammierer** [comment]
If it isn't faster, zipping is not an advance for me. I tried `platform db:dump --stdout | gzip > ./my-dump.sql.gz` it took 18 minutes for the dump.

`Importing with "SET autocommit=0 ; source dump.sql ; COMMIT ; ` is faster then dumping and works fine. I will test also `mysql -h localhost -u someuser -D somedatabase -p < my-dump.sql` .

Thank you!!!

**Comment by pjcdawkins** [comment]
You can add that `SET autocommit` stuff when importing a gzipped file too...

```
(
    echo "SET unique_checks=0, autocommit=0;"
    gunzip -dc my-dump.sql.gz
    echo "COMMIT;"
    echo "SET unique_checks=1;"
) | mysql -h localhost -u someuser -D somedatabase -p
```

but these are all small shell techniques for optimizing the same thing; it shouldn't make much of a difference what you use.

**Comment by pjcdawkins** [comment]
Looks like all questions are answered in here.

For a gzipped SQL dump, you can now use `platform sql -z` (since [v3.11.0](https://github.com/platformsh/platformsh-cli/releases/tag/v3.11.0))

**Comment by apotek** [comment]
Anyone know what role the user has to have (viewer, contributor, or admin) in order to be able to perform the db:dump or environment:sql-dump actions? Docs don't say. Does this fall under the "execute actions" permission? or under the "view" permissions?

**Comment by pjcdawkins** [comment]
@apotek you need SSH access, so that's `admin` or `contributor` on the environment, by default https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#access
