### ISSUE TITLE
New (pull request) build do not provide a drush alias immediately

### ISSUE THREAD

**Issue by andreiashu** [platformsh/platformsh-cli#539]
We run platform.sh build/deployments for github PRs and most of the process is pretty good. One thing that I stumbled upon is that running `platform drush-aliases --recreate` after a deployment that was kicked off by a PR finishes will not find the new environment.

To be clear, this is the current workflow:

- I open a new pull request say PR 10
- platform pulls the new code, builds and deploys it. In our .platform.app.yaml deployment hook we ping a remote server (server B) to start a functional test build
- server B needs to access certain drush commands on the platform server so it'll authenticate (via token) with platform.sh and then run `platform drush-aliases --recreate` to import all the drush aliases
- for an existing branch the previous steps results in successfully importing the required drush alias. For a pull request it looks like one needs to wait several minutes before that alias becomes _visible_ to `platform drush-aliases --recreate`

This might not be a cli related issue but more of a core platform issue (eventual consistency?)

**Comment by pjcdawkins** [comment]
There is unlikely to be any difference between a new pull request branch, and a new branch created via another method (e.g. `platform branch`).

The Platform.sh environment needs to have an SSH URL and a public URL before the Drush alias will be created. 

Our API doesn't (or can't) expose those URLs until the environment has been deployed for the first time. (It actually also hides those URLs whenever the environment is redeploying, which I think is a mistake.)

There are probably ways those URLs can be exposed earlier/faster, or more often. But those are issues with our API, really, they are not directly related to the CLI. I'll raise those issues internally.

**Comment by pjcdawkins** [comment]
The environment URLs are now exposed in the API a little earlier, and are not hidden anymore when an environment is redeploying.
