### ISSUE TITLE
Log files missing from environments:log

### ISSUE THREAD

**Issue by mrkschan** [platformsh/platformsh-cli#544]
In nodejs / python / ruby application container, there is /var/log/app.log.

In php application container, there is /var/log/php.access.log.

Shall we include these in environments:log?

**Comment by pjcdawkins** [comment]
The command SSHs in, and runs `ls -1 /var/log/*.log` - is that somehow failing?

**Comment by pjcdawkins** [comment]
Also, `platform log app` will work (regardless of the list it shows you if you run `platform log` with no arguments)

**Comment by mrkschan** [comment]
I probably be wrong. i just read https://github.com/platformsh/platformsh-cli/blob/development/src/Command/Environment/EnvironmentLogCommand.php#L113-L119.

**Comment by pjcdawkins** [comment]
Ah, that bit is just for the autocomplete (`platform log <TAB>`)
