### ISSUE TITLE
platform build error

### ISSUE THREAD

**Issue by webprogrammierer** [platformsh/platformsh-cli#546]
`platform build` always shows this error:

> [RuntimeException]
> Failed to move profile directory to: /var/www/platform.sh/myproject/.platform/local/builds/default-tmp/public/profiles/my_profile

and terminates build process.

All the directories have this file permissions: drwxrwxrwx 1

At this project platform.sh build mode is: "Profile mode".

I can't find out why this error occurs. How can I find more information about this error or how can I solve this problem.

I already tried to build with the -c option (`platform build -c`), this works besser, but in this case other problems occur (see my other issue).

How can I solve this "Failed to move profile directory" problem?
Thank you.

**Comment by pjcdawkins** [comment]
Hi, what's your Drush version?

If you run `platform build -vvv`, it will turn on Drush debugging - that may help.

**Comment by webprogrammierer** [comment]
Thank you. I will try `platform build -vvv` when I have problems again.

In the meantime I found a solution by myself:
Windows Explorer has to be close before running the 
`platform build`
command and Windows Explorer has to stay closed during build process.
Solved.
