### ISSUE TITLE
Unhandeled AccessDeniedException 

### ISSUE THREAD

**Issue by mrkschan** [platformsh/platformsh-cli#547]
CLI version 3.8.1

```
platform environment:sql "SHOW VARIABLES"

[AccessDeniedException]
RecursiveDirectoryIterator::__construct(/path/to/dir/subdir): failed to open dir: Permission denied


[UnexpectedValueException]
RecursiveDirectoryIterator::__construct(/path/to/dir/subdir): failed to open dir: Permission denied

Usage: platform db:sql [-p|--project PROJECT] [--host HOST] [-e|--environment ENVIRONMENT] [-A|--app APP] [--] [<query>]

For more information, type: platform help db:sql

```

The directory causing the exception is a subdirectory of the working directory.

Note, issue does not occur when used with -A option.

(Details in support ticket 12612)

**Comment by pjcdawkins** [comment]
Yeah, it's because we don't have #373 - the CLI searches the repository to find a list of applications.

The user should just run something like:

```sh
chmod -R u+rx path/to/subdir
```

**Comment by tkn98** [comment]
I think the CLI can handle these access denies more gratefully which should re-enable it to detect the application again. I have a docker setup over here where I run into it b/c docker creates some sub-trees, however from the docker-running system these created directories are not so interesting and I see no reason to change file-settings there.

Searching for application should really deal more greatfully with access denies errors. There are plenty of reasons which you should not assume full access and error-freeness with I/O.

**Comment by pjcdawkins** [comment]
The commit above is in version [3.9.0](https://github.com/platformsh/platformsh-cli/releases/tag/v3.9.0) and should resolve the issue

**Comment by tkn98** [comment]
Thanks for the fix, I don't see the exception any longer however even I'm inside a readable folder of the application, the `platform` command is unable to detect the application and asks for it.

From our end we'd say that detection should be possible. Just FYI, I can ran some tests if you like.

**Comment by tkn98** [comment]
I should add that we're using multi-app.

**Comment by pjcdawkins** [comment]
@tkn98 how about the `platform apps` command? does it show a correct list?

**Comment by tkn98** [comment]
@pjcdawkins: yes it does. But I perhaps get rid of the exceptions as I managed to tell docker to serve from my userid so it's more transparent and all files should be accessible (at least at large). So I can't do much of all testing.

**Comment by tkn98** [comment]
No more crash and instead I get a list to choose from interactively. So this is much better than before.

the `app:list ` command works like a charm.
