### ISSUE TITLE
Installer OSX passes checks but fails with SSL error

### ISSUE THREAD

**Issue by simesy** [platformsh/platformsh-cli#550]
[si]  ~$ curl -sS https://platform.sh/cli/installer | php
Platform.sh CLI installer

Environment check
  [*] The PHP version is supported: 5.6.25.
  [*] The "json" PHP extension is installed.
  [*] The "phar" PHP extension is installed.
  [*] Git is installed.
  [*] The "openssl" PHP extension is installed.
  [*] The "curl" PHP extension is installed.
  [*] The "ctype" PHP extension is installed.
  [*] The "mbstring" and/or "iconv" PHP extensions are installed.
  [*] The "allow_url_fopen" setting is on.
  [*] The "apc.enable_cli" setting is off.

Download
  Finding the latest version...

Error (2): file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by simesy** [comment]
Perusing the problem, maybe nothing that platform can do about it, but if I find a solution for me I'll post back.

**Comment by pjcdawkins** [comment]
It sounds like you need to configure your `openssl.cafile` setting in `php.ini` - possibly you have a cert file in `/usr/local/etc/openssl/cert.pem` ? Or you can download one from https://curl.haxx.se/ca/cacert.pem

**Comment by simesy** [comment]
Basically I've tried variations on these things:
-- downloading cacert.pem
-- running `php -r "print_r(openssl_get_cert_locations());"` and debugging cacert files it points to
-- `brew install openssl` and using it's certs
-- Setting `SSL_CERT_FILE` to a valid cert
-- Installing PHP 5.6, after suspecting OSX's one
-- deleting all my manner of root certificates in the keychain

I think it's something about OSX. I'm just going to add a VM to the project and install CLI inside it with ansible for the time being.

**Comment by pjcdawkins** [comment]
Ouch.

It's common for OS X users to have no cafile configured, but in all other cases I know of, configuring that has resolved the problem. I use OS X myself.

**Comment by simesy** [comment]
Yeah it smells funny. maybe a migration issue from the previous Mac.

**Comment by gmagno** [comment]
Just in case it helps someone else.
I also hit the same issue mentioned by OP, but I am running an Ubuntu:

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.5 LTS
    Release:	16.04
    Codename:	xenial

And:

    PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )
    Copyright (c) 1997-2017 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
        with Zend OPcache v7.0.32-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

And this is the output of the installation:

    Platform.sh CLI installer

    Environment check
    [*] The PHP version is supported: 7.0.32-0ubuntu0.16.04.1.
    [*] The "json" PHP extension is installed.
    [*] The "phar" PHP extension is installed.
    [*] Git is installed.
    [*] The "openssl" PHP extension is installed.
    [*] The "curl" PHP extension is installed.
    [*] The "ctype" PHP extension is installed.
    [*] The "mbstring" and/or "iconv" PHP extensions are installed.
    [*] The "allow_url_fopen" setting is on.
    [*] The "apc.enable_cli" setting is off.

    Download
    ---------------------
    Finding the latest version...
    **************************
    latest->url: https://github.com/platformsh/platformsh-cli/releases/download/v3.39.0/platform.phar
    Downloading version 3.39.0...

    Error (2): file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
    error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

I ended up going with a "quick & dirty™" [solution](https://stackoverflow.com/a/40311146/1278365).

**Comment by pjcdawkins** [comment]
Closing mainly because it's outdated. There's a somewhat related (but different) issue in #990 which should now be solved.
