### ISSUE TITLE
Why does the login expire and how to avoid this?

### ISSUE THREAD

**Issue by webprogrammierer** [platformsh/platformsh-cli#571]
```
  [LoginRequiredException]
  Invalid refresh token.
  Please log in again by running: platform login
```

We are running a snapshot.sh every night (cron).

It failes when the login has expired.

But what is the reason for the expired login?
How can we find out that the login expired?
How can we avoid that login expires?

Do we have to check every day or do we have to login every day to avoid the error above?
Thank you.

**Comment by pjcdawkins** [comment]
There is no reason why it should ever happen. But ... it still does, apparently.

If you need to preserve authentication in a non-interactive script, the easiest solution is, I think, is to use an API token:
1. Get an API token in [Platform.sh Accounts](https://accounts.platform.sh) -> Account Settings -> API Tokens
2. Save it to a file (with restricted permissions, e.g. `chmod 400 my-api-token-file`)
3. Add this to `~/.platformsh/config.yaml`:
    
    ```yaml
    api:
      token_file: /path/to/my-api-token-file
    ```
  
    (as documented in [Customization](https://github.com/platformsh/platformsh-cli/tree/9c55e77c94813be9049c631e225db45a1c128711#customization) in the README)

**Comment by pjcdawkins** [comment]
The login options are now described in `platform help login` and here:
https://github.com/platformsh/platformsh-cli#authentication
