### ISSUE TITLE
have platform build symlink locally for wordpress the same as drupal

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-cli#577]
I am developing for a wordpress site on platform but coming from very used to drupal I miss a few things that I'd think it should be easy/good to implement.

`wp-config.php`, plugins and themes are copied by platform build instead of symlinked (which should happen locally only), which means that you have to `platform build` on every change.

Drupal, on the other hand, properly symlink both local modules and themes, so you can edit them and see the changes live on your local dev.

Would it be possible to improve this?

**Comment by xtfer** [comment]
This actually comes from the project, not the CLI. I'm assuming you've copied from our WordPress composer starter project, so the relevant code is in https://github.com/platformsh/platformsh-example-wordpress-composer/blob/master/.platform.app.yaml. If you have a better solution, please open a PR against that project so we can improve it for everyone. :)
