### ISSUE TITLE
Difference between first "platform build" and second "platform build" in regard to symlinks

### ISSUE THREAD

**Issue by scotthooker** [platformsh/platformsh-cli#578]
Hi @pjcdawkins / Platform :) 

We're building some automation around local dev, deployments etc... and one of our stumbling blocks appears to be a difference between the initial run of `platform build` compared to any subsequent platform builds. 

The difference is the path of the builds directory. 

E.g. First platform build

`Cleaning up...
smp:scotttest Scott$ cd .platform/local/
smp:local Scott$ ls
builds	deps	shared
smp:local Scott$ cd builds/
smp:builds Scott$ ls -l
total 8
lrwxr-xr-x  1 Scott  staff  22 16 Mar 12:04 default -> /Users/Scott/scotttest`

Compared to any subsequent platform build

`smp:scotttest Scott$ cd .platform/local/
smp:local Scott$ ls -l
total 0
drwxr-xr-x  3 Scott  staff  102 16 Mar 12:05 builds
drwxr-xr-x  3 Scott  staff  102 16 Mar 12:04 deps
drwxr-xr-x  3 Scott  staff  102 16 Mar 12:04 shared
smp:local Scott$ cd builds/
smp:builds Scott$ ls -l
total 8
lrwxr-xr-x  1 Scott  staff  8 16 Mar 12:05 default -> ../../..
smp:builds Scott$ platform --version
Platform.sh CLI 3.14.0
`

The second time round the symlinks are relative and thus "better" transportable and reliable.

**Comment by pjcdawkins** [comment]
Fixed in 3.14.1 - you should get the relative link each time now
