### ISSUE TITLE
Add a  ``--wait`` parameter to all operations

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-cli#58]
This waits for the operation to complete or time-out after a while (10 minutes?).

As a Platform CLI user, I want a Platform ``environment:status`` command that lets me know when an environment is done building.

An extra flag ``-f``, should specify the return output format (JSON, XML, default=plaintext)

Statuses should be: ``Building``, ``Ready``, ``Unavailable``, ``Active``, ``Inactive``.

**Comment by pjcdawkins** [comment]
This will be solved in version 2.x, where long-running commands have a `--no-wait` option (they wait by default)
