### ISSUE TITLE
Don't add bashisms to .profile

### ISSUE THREAD

**Issue by andriokha** [platformsh/platformsh-cli#585]
Hi,

I install platform-cli on a fresh Linux Mint 18.1. It adds a line to `~/.profile` that sources in a bash script. If I log out and log back in, X fails immediately. I think this is because of [bashisms](http://mywiki.wooledge.org/Bashism) directly in shell-config.rc as well as in the output of `platform _completion -g -p platform`. (Looks like [a similar problem here](http://askubuntu.com/a/26369).)

I guess it makes sense to either unbashify the scripts or to require them to be sourced from bash-specific config files (eg. `.bash_profile`).

Thanks

**Comment by pjcdawkins** [comment]
This was resolved at least several months ago.

The relevant installation logic is now all within the `self:install` command within the CLI (it used to be in a separate installer script):
https://github.com/platformsh/platformsh-cli/blob/8baebb450776fc9fed22867bed25d1bb9f0b0083/src/Command/Self/SelfInstallCommand.php

The command ensures the existence of a `~/.platformsh/shell-config.rc` file, and then adds these lines to `.bashrc` or a similar file (if detected):

```sh
# BEGIN SNIPPET: Automatically added by the Platform.sh CLI
export PATH='/Users/alice/.platformsh/bin':"$PATH"
. '/Users/alice/.platformsh/shell-config.rc' # END SNIPPET
```

The `shell-config.rc` file should work in every shell that sources it:

https://github.com/platformsh/platformsh-cli/blob/8baebb450776fc9fed22867bed25d1bb9f0b0083/shell-config.rc
