### ISSUE TITLE
shell-config.rc breaks Linux GUI login

### ISSUE THREAD

**Issue by Crell** [platformsh/platformsh-cli#588]
This issue was reported on Docs, but really belongs here:

https://github.com/platformsh/platformsh-docs/issues/500

**Comment by pjcdawkins** [comment]
The `shell-config.rc` contains Bashisms, so it's only going to work on Bash-like shells (Bash, ZSH, Dash... probably others).

I have temporarily fixed the installer not to write to `.profile`, as suggested in https://github.com/platformsh/platformsh-cli/issues/585

The next step is:
* allow writing to `.profile`, but only cross-shell-compatible config (i.e. just the PATH export)

**Comment by pjcdawkins** [comment]
This should now be resolved. See also https://github.com/platformsh/platformsh-cli/issues/585#issuecomment-366440599
