### ISSUE TITLE
"Not logged in" exception after logged in

### ISSUE THREAD

**Issue by OndraM** [platformsh/platformsh-cli#596]
Hi,
I just logged in using platform.sh CLI console, and the confirmation I get after logging in is RuntimeException "Not logged in", which is I guess not intentional :).

This is all what I've done:

![platformsh-login](https://cloud.githubusercontent.com/assets/793041/25568283/9def46ac-2dff-11e7-8863-30873ea83684.png)

Note I actually am logged in despite the error, and can fully use the console as a logged user.

This is fully reproducible for me after running `platform logout --all` and repeating the login proces.

**Comment by pjcdawkins** [comment]
Thanks. It looks like the bug has been present since version 3.10.0. Working on a fix now...

**Comment by pjcdawkins** [comment]
Fixed in version 3.15.2. Many thanks for the report!

**Comment by OndraM** [comment]
@pjcdawkins Great, thanks for the fast fix!
