### ISSUE TITLE
Project not found platform cli not working

### ISSUE THREAD

**Issue by xvendo** [platformsh/platformsh-cli#604]
I created a dev trial. Installed platform cli. Then I deleted the project.
I created a different account on platform, created project structure.
But if I want to enter platform I will be asked for user/email. 
So I entered my new user/email on platform.sh and my password.

The following error occurs!

[ProjectNotFoundException]                                        
  Project not found: https://eu.platform.sh/projects/dlwbryoqqmem4  
  The project probably no longer exists. 

Platform is pointing to a deleted project!
![platform_errors](https://cloud.githubusercontent.com/assets/8666348/26511201/d9588894-4258-11e7-9582-63eddda2cd70.png)

**Comment by xvendo** [comment]
I fixed this. There is a .platform folder and inside this there is a local folder where your project.yaml file resides.

You have to change the following in this file:
id: YOURPROJECTID
host: eu.platform.sh

Then you are done

**Comment by pjcdawkins** [comment]
See also `platform help project:set-remote`
