### ISSUE TITLE
Platform log kill leaking process

### ISSUE THREAD

**Issue by luxifer** [platformsh/platformsh-cli#606]
If the `platforn log` command gets kill by `SIGTERM` or `SIGINT`, the `ssh` process to tail the log is still up.
```
$ pstree -p 68145
-+= 00001 root /sbin/launchd
 \-+= 08550 florent /Applications/iTerm.app/Contents/MacOS/iTerm2
   \-+= 19860 florent /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fp florent
     \-+= 19861 root login -fp florent
       \-+= 19862 florent -zsh
         \-+= 68145 florent php /Users/florent/.platformsh/bin/platform log -p ************* -e master access --tail
           \--- 68152 florent ssh -C ****************************@ssh.eu.platform.sh tail -n 100 '/var/log/access.log' -f

$ kill -s INT 68145

$ pstree -p 68152
-+= 00001 root /sbin/launchd
 \--- 68152 florent ssh -C ****************************@ssh.eu.platform.sh tail -n 100 '/var/log/access.log' -f
```

I tried with a simple program and I got the same result. I think it's because in `Platformsh\Cli\Service\Shell::executeSimple` the pipes `$pipes` are not closed before `proc_close` is called. I'm trying something with `pcntl_signal` to close the pipes when the `platform` process gets killed.

**Comment by pjcdawkins** [comment]
SIGINT isn't supposed to kill child processes, AFAIK.
https://unix.stackexchange.com/questions/149741/why-is-sigint-not-propagated-to-child-process-when-sent-to-its-parent-process

**Comment by luxifer** [comment]
The same happens with `SIGTERM`, but if I kill the `platform log` process with <kbd>Ctrl</kbd>+<kbd>C</kbd> the child ssh process gets killed too.

**Comment by pjcdawkins** [comment]
See the link above: <kbd>Ctrl</kbd>+<kbd>C</kbd> sends a signal to the process group ID, not the process PID

**Comment by luxifer** [comment]
Simple PHP script to reproduce the error:
```php
<?php
$commandline = "ssh -C ****************************@ssh.eu.platform.sh tail '/var/log/access.log' -f";
$process = proc_open($commandline, [STDIN, STDOUT, STDERR], $pipes);
exit(proc_close($process));
```
What happens:
```shell
$ pstree -p 72491
-+= 00001 root /sbin/launchd
 \-+= 08550 florent /Applications/iTerm.app/Contents/MacOS/iTerm2
   \-+= 19860 florent /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fp florent
     \-+= 19861 root login -fp florent
       \-+= 19862 florent -zsh
         \-+= 72491 florent php proctest.php
           \--- 72492 florent ssh -C ****************************@ssh.eu.platform.sh tail /var/log/access.log -f

$ kill -s TERM 72491

$ pstree -p 72492
-+= 00001 root /sbin/launchd
 \--- 72492 florent ssh -C ****************************@ssh.eu.platform.sh tail /var/log/access.log -f
```

**Comment by pjcdawkins** [comment]
This is normal behaviour. If you want the `ssh` process to stop too, you should kill the process group, not just the `php` PID.

**Comment by luxifer** [comment]
Thanks for the explanation. I'll try that tomorrow morning

**Comment by luxifer** [comment]
Sending the signal to the group does the job. Thanks again.
