### ISSUE TITLE
Use local drush if applicable

### ISSUE THREAD

**Issue by ralt** [platformsh/platformsh-cli#620]
When drush is installed locally with just `composer require drush/drush`, `platformsh-cli` should use it, and not silently fail as it currently does, if drush isn't installed globally.

Notably, the `platform drush-aliases` command acts this way.

**Comment by ralt** [comment]
@pjcdawkins related is the fact that the CLI is silently displaying "Created drush aliases" even if it failed; do you want another issue for it?

**Comment by pjcdawkins** [comment]
It can (and does) create Drush aliases even if it can't find Drush (it just writes directly to `~/.drush/<group>.aliases.drushrc.php`)

**Comment by ralt** [comment]
Ok, my bad then!
