### ISSUE TITLE
Failing deploys through new easy install on platform.sh

### ISSUE THREAD

**Issue by patkar** [platformsh/platformsh-cli#622]
Hi, I appreciate the changes from #617 for more easy install on platform.sh (especially the writable dir thingy), but this lines are causing headaches:
https://github.com/platformsh/platformsh-cli/blob/dfdb0006cc038bf6d3afe82e2445791c89513c5e/dist/installer.php#L378-L383

With this you're now adding the sourcing to `.environment` instead of e.g. `.bash_profile` (exists on our projects). Although you're correctly sourcing it with `.` instead of `source`
https://github.com/platformsh/platformsh-cli/blob/dfdb0006cc038bf6d3afe82e2445791c89513c5e/dist/installer.php#L246-L249
deployments fail, because the sourced `shell-config.rc` is not dash compatible and it seems the shebang is ignored on sourcing.

I know, there is a `|| true` at the end of the sourcing, so I'm somehow confused why this is failing. But it does on every project of ours, where we are installing the CLI in the build hook.

According to @ralt  `.environment` is loaded so early and before executing the deploy hook, so the deploy hook fails with exit code `2` in the system (and without error reporting in the `deploy.log`). I think he can describe the internal problem with it better :smirk: 

This problem is similar to #588 and #585, where you shouldn't add the sourcing of bashisms to files which may be executed by other shells than bash, which the `.environment` file is.

**Comment by pjcdawkins** [comment]
Ah 🤦‍♂️  I didn't test through a Dash deploy/cron hook. It probably wants to test for Bash before including the file with Bash dependencies (which is for autocompletion, not useful/relevant anyway).

**Comment by pjcdawkins** [comment]
This should now be resolved. See also https://github.com/platformsh/platformsh-cli/issues/585#issuecomment-366440599
