### ISSUE TITLE
Unknown SSL protocol error on login (mac)

### ISSUE THREAD

**Issue by ShenolHusein** [platformsh/platformsh-cli#631]
hi, 
i am getting an SSL Error on login: 

[ConnectException]
cURL error 35: Unknown SSL protocol error in connection to accounts.platform.sh:443

openssl version : OpenSSL 1.0.2l

is this a known issue?

**Comment by pjcdawkins** [comment]
I have not seen that before.

I use a Mac, and my OpenSSL version is `OpenSSL 0.9.8zh 14 Jan 2016`, and my cURL version is `curl 7.52.1 (x86_64-apple-darwin15.6.0) libcurl/7.52.1 SecureTransport zlib/1.2.8`. What's your cURL version?

The Qualys SSL test for `accounts.platform.sh` is https://www.ssllabs.com/ssltest/analyze.html?d=accounts.platform.sh&hideResults=on&latest and it shows:
* grade A+
* TLS 1.2
* simulated handshake passes with OpenSSL 1.0.2e and 1.0.1l

**Comment by ShenolHusein** [comment]
hi here are my curl and openssl version:
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
OpenSSL 0.9.8zh 14 Jan 2016

but still not working always getting 
[ConnectException]
cURL error 35: Unknown SSL protocol error in connection to accounts.platform.sh:443

**Comment by pjcdawkins** [comment]
Those versions should be fine. Did you use Homebrew to install PHP/curl/openssl?

If so, can you try reinstalling PHP, linking it against Homebrew's curl? See this Gist for an example:

https://gist.github.com/ryanscherler/fea4bb75379c1564df7e027c45615cc9#file-php-openssl-md

**Comment by pjcdawkins** [comment]
If you're lucky, it might just be a case of:

```sh
brew reinstall php71 --with-openssl
```

**Comment by ShenolHusein** [comment]
Since i am using MAMP for my local Environment,
during Installation it adds some export PATH= in to .bash_profile and that was making trouble.

Anyway thanks for the Help.
