### ISSUE TITLE
CLI stuck in a autoupdate loop and break

### ISSUE THREAD

**Issue by gnufred** [platformsh/platformsh-cli#642]
When the script live in a non-writable location, like `/usr/bin/platformsh` on Archlinux for example, I keep getting this error whatever I do.

```
platform project:curl -p ID /settings
Checking for Platform.sh CLI updates (current version: 3.22.2)
```

I had uninstall the script and reinstall manually instead of user the package manager.

**Comment by pjcdawkins** [comment]
That's not really an error message. Does it exit, or just hang? It's simply fetching https://platform.sh/cli/manifest.json via PHP's `file_get_contents()` (which should be quick), and then it won't do anything if it doesn't find a new version.

Are you using a proxy? That might affect the request.

Auto-updates can be switched off if necessary (https://github.com/platformsh/platformsh-cli#customization).

**Comment by gnufred** [comment]
This error occurs on Archlinux while using the `yaourt -S platformsh-cli` AUR installer.

I guess the installer script should disable auto-updates as the update will be managed by AUR updater.

**Comment by pjcdawkins** [comment]
Nevertheless, it's strange that the "Checking for updates" message should display and hang: it is just downloading a JSON file over HTTP/TLS. The CLI needs to be able to make similar requests all the time.

**Comment by gnufred** [comment]
I will investigate the source to see what cause this behavior and try to fix if able.

**Comment by pjcdawkins** [comment]
This may help: see if PHP CLI can download that file on its own:

```sh
php -r 'echo file_get_contents("https://platform.sh/cli/manifest.json");'
```

**Comment by gnufred** [comment]
I reinstalled and it work just fine. No idea what the problem was.

Most certainly my setup.
