### ISSUE TITLE
Support for drush 9.0.0-rc1 (changed alias file naming convention again)

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-cli#655]
See 

https://github.com/drush-ops/drush/releases/tag/9.0.0-rc1
> Simplified site aliases. Fixes #3107 (#3184)

More specifically: https://github.com/drush-ops/drush/issues/3107#issuecomment-340040803

I updated drush and was driving me nuts why aliases were not there.

Renaming `group.alias.yml` to `group.site.yml`

Kind of worked.

There's another issue though, which is that running `platform drush-aliases -r` now doesn't work because it runs:

`drush @none sa @OLDGROUP`

If you are creating aliases for the first time and group is not there, before it simply return a string but the command was OK, now it throws an exception so the aliases can't be generated.

The above becomes the norm when you update drush as it simply find no aliases.

See: https://github.com/platformsh/platformsh-cli/blob/71b40df52a5534acb801e634f5c08595d2e1f2d6/src/Service/Drush.php#L230

**Comment by pjcdawkins** [comment]
I'm not sure I understand the last part - what exception is thrown? It's supposed to be OK with no aliases being found:
https://github.com/platformsh/platformsh-cli/blob/71b40df52a5534acb801e634f5c08595d2e1f2d6/src/Service/Drush.php#L242-L246

**Comment by pjcdawkins** [comment]
Ah... reproduced
