### ISSUE TITLE
Failed to connect to the Platform.sh Git server

### ISSUE THREAD

**Issue by mtamma** [platformsh/platformsh-cli#673]
Hi,

Can I anyone tell me about an issue that i faced when running command 'platform get' in my console?

Result when typing 'platform get'
` $ platform get`
`Directory [ihg-ic-perth]:`
`Environment [master]:`
`Failed to connect to the Platform.sh Git server`

`Please check your SSH credentials`
`You can list your keys with: platform ssh-keys`

List ssh-keys that exist on my accont
`$ platform ssh-keys`
`Your SSH keys are:`
`+-------+---------+----------------------------------+`
`| ID    | Title   | Fingerprint                      |`
`+-------+---------+----------------------------------+`
`| 64075 | laptop  | 23c3ccc08a9d0ef0996538ff4a6c8ba5 |`
`| 65117 | new key | f315c8bfdc115cec1f0232dc4f44983b |`
`| 65156 | desktop | 9400b4a09895e60d973ccfcdfaaf657d |`
`+-------+---------+----------------------------------+`

`Add a new SSH key with: platform ssh-key:add`
`Delete an SSH key with: platform ssh-key:delete [id]`

And this the the ssh-key that load on my console
`$ ssh-add -l`
`2048 23:c3:cc:c0:8a:9d:0e:f0:99:65:38:ff:4a:6c:8b:a5 /c/Users/ADMIN/.ssh/id_rsa.komosion (RSA)`

This the result when trying to run command 'ssh -v'
`$ ssh -v git.au.platform.sh`
>OpenSSH_6.6.1, OpenSSL 1.0.1m 19 Mar 2015
debug1: Connecting to git.au.platform.sh [13.54.222.56] port 22.
debug1: Connection established.
debug1: identity file /c/Users/ADMIN/.ssh/id_rsa type 1
debug1: identity file /c/Users/ADMIN/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_dsa type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/ADMIN/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: Remote protocol version 2.0, remote software version Platform.sh
debug1: no match: Platform.sh
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha2-256-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha2-256-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: RSA ce:7f:e5:f5:91:15:76:8a:03:a1:9b:f2:b2:a2:48:6b
debug1: Host 'git.au.platform.sh' is known and matches the RSA host key.
debug1: Found key in /c/Users/ADMIN/.ssh/known_hosts:57
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /c/Users/ADMIN/.ssh/id_rsa.komosion
debug1: Server accepts key: pkalg ssh-rsa blen 279
Hello mardi-tamma (UUID: ad567a03-1fda-4f6e-842c-8d4d24cf60e7), you successfully connected, but the service ADMIN doesn't exist or you do not have access to it
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /c/Users/ADMIN/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: /c/Users/ADMIN/.ssh/id_dsa
debug1: Trying private key: /c/Users/ADMIN/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/ADMIN/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).

As you can see my account is noticed. (mardi-tamma)
`Hello mardi-tamma (UUID: ad567a03-1fda-4f6e-842c-8d4d24cf60e7), you successfully connected, but ``the service ADMIN doesn't exist or you do not have access to it`

But why i failed when run command 'platform get'?
Any help will be really appreciate.

Best Regards,

**Comment by pjcdawkins** [comment]
If this doesn't work:

```
ssh projectid@git.au.platform.sh
```

then `platform get` won't work. You'd need to make sure the key is loaded in your agent, or use the identity file argument (`-i path/to/key`).

Make sure you have the latest version of the CLI (`platform up`) - version 3.25.0 did fix a related bug.

**Comment by mtamma** [comment]
Thanks for the quick reply @pjcdawkins 

the platform version that i used is 3.26.1
`$ platform -version`
`Platform.sh CLI 3.26.1`

i think  ssh command to projectid@git.au.platform.sh is working
`$ ssh -v olh4o3uobsjkm@git.au.platform.sh`
>OpenSSH_6.6.1, OpenSSL 1.0.1i 6 Aug 2014
debug1: Reading configuration data /d/Users/Mardi Vester Tamma/.ssh/config
debug1: Connecting to git.au.platform.sh [13.54.222.56] port 22.
debug1: Connection established.
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_rsa type 1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_rsa-cert type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_dsa type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_dsa-cert type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_ecdsa type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_ecdsa-cert type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_ed25519 type -1
debug1: identity file /d/Users/Mardi Vester Tamma/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1
debug1: Remote protocol version 2.0, remote software version Platform.sh
debug1: no match: Platform.sh
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-sha2-256-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-sha2-256-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: RSA ce:7f:e5:f5:91:15:76:8a:03:a1:9b:f2:b2:a2:48:6b
debug1: Host 'git.au.platform.sh' is known and matches the RSA host key.
debug1: Found key in /d/Users/Mardi Vester Tamma/.ssh/known_hosts:22
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /d/Users/Mardi Vester Tamma/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /d/Users/Mardi Vester Tamma/.ssh/id_rsa_bitbucket
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /d/Users/Mardi Vester Tamma/.ssh/id_rsa.komosion
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to git.au.platform.sh ([13.54.222.56]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0

>mardi-tamma <mardi.tamma@sitemaster.com.au>, welcome to Platform.sh, you successfully connected, but there is no shell here.

>Version: 2.7.12

>debug1: channel 0: free: client-session, nchannels 1
Connection to git.au.platform.sh closed.
Transferred: sent 4540, received 1892 bytes, in 0.6 seconds
Bytes per second: sent 7814.1, received 3256.5
debug1: Exit status 255

is there some config or option or parameter that i could use to inject '-i [ssh key path]' on platform get command, something like:
`platform get projectId -i ~/.ssh/id_rsa`

**Comment by pjcdawkins** [comment]
Yes, you can use `-i` in any relevant CLI command:

```sh
platform get olh4o3uobsjkm -i ~/.ssh/id_rsa.komosion
```

but I don't understand why your SSH agent isn't being used.

**Comment by mtamma** [comment]
@pjcdawkins the -i command still not work on my case

`$ platform get olh4o3uobsjkm -i ~/.ssh/id_rsa.komosion -vvv`
`DEBUG Selected project: olh4o3uobsjkm`
`Directory [ihg-ic-perth]:`
`DEBUG Finding the project root`
`DEBUG Project root not found`
`Environment [master]:`
`DEBUG Selected environment: master`
`Running command: where git`
`Running command: git --version`
`Running command: git ls-remote olh4o3uobsjkm@git.au.platform.sh:olh4o3uobsjkm.git HEAD`
`  Using additional environment variables:`
`    GIT_SSH=D:\Users\Mardi Vester Tamma\AppData\Local\Temp\cliF162.tmp`
`Failed to connect to the Platform.sh Git server`

`Please check your SSH credentials`
`You can list your keys with: platform ssh-keys`

I might could use '~/.ssh/config` file to set git.au.platform.sh to use specific ssh key. but have no clue about the user that going to use. is it git (the same like used by bitbucket).
something like:
`Host git.au.platform.sh`
`    User git`
`    Hostname git.au.platform.sh`
`    IdentityFile ~/.ssh/id_rsa.komosion`

btw the config above still not work for my case.

**Comment by pjcdawkins** [comment]
As far as I know you don't need to be that precise in SSH config, you can also use:

```
Host *.platform.sh
IdentityFile ~/.ssh/id_rsa.komosion
```

**Comment by mtamma** [comment]
i think the problem was on my git version. somehow the ssh agent isn't being used like mentioned by @pjcdawkins 
after update the git version into the latest version (v2.15)
I am able to get the project now.
`$ platform get`
>Directory [ihg-ic-perth]:
Environment [master]:
Downloading project ihg-ic-perth (olh4o3uobsjkm)
  Cloning into 'D:\SourceCode\Komosion/ihg-ic-perth'...
  remote: counting objects: 5816, done.
Receiving objects: 100% (5816/5816), 14.07 MiB | 760.00 KiB/s, done.
Resolving deltas: 100% (1585/1585), done.

>The project ihg-ic-perth (olh4o3uobsjkm) was successfully downloaded to: ihg-ic-perth/

>Creating Drush aliases in the group @ihg-ic-perth
>Creating ~/.drush/drush.yml file to configure the global alias-path

>You can build the project with:
    cd ihg-ic-perth/
    platform build

Thank you so much for your time @pjcdawkins

**Comment by pjcdawkins** [comment]
Good to know, thanks @mtamma
