### ISSUE TITLE
User defined site aliases are prefixed with '@' when generated with drush-aliases

### ISSUE THREAD

**Issue by GROwen** [platformsh/platformsh-cli#677]
When running `platform drush-aliases` it's expected that any existing user defined aliases are preserved. This is the case however they are altered and prefixed with an `@` symbol.

Any user defined aliases that exist in `{alias_group}.site.yml` are prefixed with an `@` symbol on each run of `platform drush-aliases` resulting in aliases like `@alias_group.@userdefined` on the first run and `@alias_group.@@userdefined`.

**Comment by pjcdawkins** [comment]
Fixed in v3.28.0
