### ISSUE TITLE
Activity log should prompt to follow latest "in progress" activity.

### ISSUE THREAD

**Issue by mglaman** [platformsh/platformsh-cli#691]
A really nice feature would be to prompt the user if they would like to execute `activity:log LOG_ID` on the latest "in progress" activity.

I have something like that here when checking DrupalCI jobs: https://github.com/mglaman/drupalorg-cli/blob/master/src/Cli/Command/DrupalCi/ListResults.php#L74

If something is running, offer to follow it.

I know it would save me a lot of time

**Comment by pjcdawkins** [comment]
If you don't specify an ID, `platform activity:log` by default picks the latest activity (whether complete, pending or in progress) - it doesn't interact.

https://github.com/platformsh/platformsh-cli/blob/b7cb2f2d287405fe6da7453634498b7c08aa63b0/src/Command/Activity/ActivityLogCommand.php#L58-L73

What should change here exactly?

**Comment by mglaman** [comment]
Nothing, then :) I was ignorant of that fact.

**Comment by pjcdawkins** [comment]
Good to hear! Also: use the `--all` (`-a`) option if you don't want to filter by environment (see `platform ac:log -h`)
