### ISSUE TITLE
Gitlab integration, build_request_merge false to false not working when creating it

### ISSUE THREAD

**Issue by hanoii** [platformsh/platformsh-cli#697]
I was adding a Gitlab Integration to a new project and I answered No to the build-merge-requests question, but when the information came back, I saw all in true.

I then tried the same with the `--build-merge-requests=false` added to the command line, same behavior.

I then tried `platform integration:update IID --build-merge-requests=false` and that seemed to work.

**Comment by pjcdawkins** [comment]
Thanks for the report - this should be fixed in `v3.31.0`
