### ISSUE TITLE
RequestException and RingException  v3.31.1

### ISSUE THREAD

**Issue by swingingtom** [platformsh/platformsh-cli#698]
Hello,
I've just updated the platformsh cli to v3.31.1 and I'm now unable to ssh my environment.

Each time I try to ssh using platform cli, I get RequestException and RingException.

`
$ platform ssh -p projectid -e master

  [RequestException]
  Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 406
  [message] fopen(): Failed to enable crypto
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 406
  [message] fopen(https://eu.platform.sh/api/projects/projectid/environments): failed to open stream: operation failed
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 406
  [message] Undefined variable: http_response_header
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 407

  [RingException]
  Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 406
  [message] fopen(): Failed to enable crypto
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 406
  [message] fopen(https://eu.platform.sh/api/projects/project/environments): failed to open stream: operation failed [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.hp
  [line] 406
  [message] Undefined variable: http_response_header
  [file] phar:///home/Thomas/.platformsh/bin/platform/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
  [line] 407
`

Im using bash ubuntu for windows.

It wasnt the case previously, so does anyone have any idea ?
Thank you.

**Comment by swingingtom** [comment]
I fixed it with installing openssl ca-certificates

`sudo apt-get install openssl ca-certificates`

Never had to do it before. May be I should have read the release note of platformshcli

**Comment by pjcdawkins** [comment]
That's not to do with the new CLI version, but we did renew our server certificates recently on all `*.platform.sh` hostnames (eu.platform.sh, us.platform.sh, etc.). At least some kind of CA certification configuration should be present and reasonably up-to-date, I don't know why you'd need to specifically install/update `ca-certificates` but that would depend on how up-to-date the OS is.

eu.platform.sh SSL analysis gives an A+ rating but does mention "Chain issues"- "Incorrect order":
https://ssllabs.com/ssltest/analyze.html?d=eu.platform.sh&hideResults=on&latest
