### ISSUE TITLE
Display the Git remote URL at the end of the `project:create` command

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-cli#720]
Feature Request

```
As a Platform.sh user, 
When I create a project with `project:create`,
I should see the Git remote URL at the end of the process,
So that I can directly add the Git remote and push my current Git repository to it
```

**Comment by pjcdawkins** [comment]
You currently get the project ID (that's the only thing that goes to stdout), and with that you can do anything:

* `platform get [id]` (to clone)
* `platform project:set-remote [id]` (to set your project ID if already in a git repository)
* `platform project:info git` (to get the Git URL)
* `platform init -e master -p [id] https://github.com/platformsh/platformsh-example-drupal8` (to initialize a project from a public repository)

**Comment by GuGuss** [comment]
I was missing the: `platform project:set-remote [id]`!

Thanks.
