### ISSUE TITLE
Environment names dont always match branch names

### ISSUE THREAD

**Issue by xtfer** [platformsh/platformsh-cli#727]
It is possible to change the Environment name via the Platform.sh ui, however the CLI still sometimes assumes the names match.

e.g I have an environment called Production using the branch master, on the project xyz123.

```
redeploy -p xyz123 -e master

Continue? [Y/n] y

Are you sure you want to redeploy the environment master? [Y/n]
```

It should probably say, `Are you sure you want to redeploy the environment Production for branch master?` or something similar

**Comment by pjcdawkins** [comment]
With the above commit, that environment will be referred to consistently as `Production (master)`.

On the command line (`-e` option, etc) environments are always specified with their ID (AKA `name` / branch name).
