### ISSUE TITLE
SSH key UX

### ISSUE THREAD

**Issue by OriPekelman** [platformsh/platformsh-cli#74]

**Comment by pjcdawkins** [comment]
Users can use `ssh -i path/to/key`, with the GIT_SSH_COMMAND env var for git (see: http://superuser.com/a/912281/183030), and the `-e` option for rsync

**Comment by OriPekelman** [comment]
There might be a bunch of stuff that wants to go to the documentation from here. ( https://github.com/platformsh/platformsh-docs/blob/master/using/use-SSH.md ) Do we close this one?

**Comment by pjcdawkins** [comment]
Yes it seems this belongs in the docs (unless we want to wrap all ssh+git+rsync commands in the CLI).

I only discovered GIT_SSH_COMMAND recently and it seems to be a good solution.
