### ISSUE TITLE
Curl error 60

### ISSUE THREAD

**Issue by staabm** [platformsh/platformsh-cli#754]
Today while setting up the tool, I was running into curl error 60, because of my php binary wasnt configured with a proper cainfo file.

Since there are a ton of problems arround this file, there are dedicated libs just to handle that.
Would be cool if this cli app could integrate https://github.com/paragonie/certainty so it will no longer depend on a proper configured cabundle file within the php.ini

**Comment by pjcdawkins** [comment]
Thanks, that sounds like a great idea.

Did you get error 60 during [installation](https://github.com/platformsh/platformsh-cli/#installation), or while running the CLI through `platform`?

If the former, I guess `paragonie/certainty` would need to be included within the [installer](https://github.com/platformsh/platformsh-cli/blob/master/dist/installer.php), which makes it heavier than it is right now - that's not necessarily a problem but maybe it needs some thought.

**Comment by staabm** [comment]
In my case I got this error while running the first platform command todo the auth.

Since the installer is using the curl cli tool, I guess it doesnt depend on ext-curl?

**Comment by staabm** [comment]
just reported the installation as a separate issue: https://github.com/platformsh/platformsh-cli/issues/755
