### ISSUE TITLE
install error: stdin is not a tty

### ISSUE THREAD

**Issue by staabm** [platformsh/platformsh-cli#755]
when running the proposed install command in my "Git Bash for Windows" which gets installed with [Github for Desktop](https://desktop.github.com/) I am running into the following error:

```
$ curl -sS https://platform.sh/cli/installer | php
stdin is not a tty
curl: (23) Failed writing body (0 != 9464)
```

using

```
$ php -v
PHP 7.2.9 (cli) (built: Aug 15 2018 23:09:20) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

Windows10x64 on latest updates

**Comment by pjcdawkins** [comment]
Thanks for the report, I'll have to try this in Git Bash to debug.

I guess the first thing I'd try is to execute some PHP through a pipe:

```sh
echo '<?php echo 14 * 3;' | php
```

**Comment by staabm** [comment]
```
$ echo '<?php echo 14 * 3;' | php
stdin is not a tty
```

**Comment by pjcdawkins** [comment]
According to [this StackOverflow answer](https://stackoverflow.com/a/33623136), Git Bash can't execute `php` through a pipe. Instead, you could probably run:

```sh
curl https://platform.sh/cli/installer -o cli-installer.php
php cli-installer.php
```

**Comment by staabm** [comment]
thanks!
