### ISSUE TITLE
undefined service error after update

### ISSUE THREAD

**Issue by tariqinaam** [platformsh/platformsh-cli#779]
i have just updated platform cli to 3.40.0 and now when pulling database from production using platform db:dump, i get service not found. verbose shows following

```
Notice: Undefined index: service in phar:///usr/local/bin/platform/src/Command/Db/DbDumpCommand.php on line 70

Exception trace:
 () at phar:///usr/local/bin/platform/vendor/platformsh/client/src/Model/Deployment/EnvironmentDeployment.php:63
 Platformsh\Client\Model\Deployment\EnvironmentDeployment->__call() at phar:///usr/local/bin/platform/src/Command/Db/DbDumpCommand.php:70
 Platformsh\Cli\Command\Db\DbDumpCommand->execute() at phar:///usr/local/bin/platform/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/platform/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/platform/src/Application.php:277
 Platformsh\Cli\Application->doRunCommand() at phar:///usr/local/bin/platform/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/platform/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/platform/bin/platform:19
 require() at /usr/local/bin/platform:10
```
Am i doing something wrong here?

**Comment by pjcdawkins** [comment]
Trying to reproduce this - could you give me a project ID here or in an email please? (patrick@platform.sh)

**Comment by tariqinaam** [comment]
@pjcdawkins I have emailed you the project id. thanks

**Comment by Boegie** [comment]
Same error here on all my projects.

Windows 10
platform.sh CLI 3.40.1

It _might_ have something to do with something I've noticed: The OpenSSH password popup appears twice instead of the usual once (and yes, I did type my password correctly)

![image](https://user-images.githubusercontent.com/18569707/52934440-bd70c880-3356-11e9-82b2-3e3ceaead0e7.png)

**Comment by pjcdawkins** [comment]
@Boegie the extra dialog box is an effect of trying to find the service name, when it doesn't exist in the application's PLATFORM_RELATIONSHIPS.

If you still get the same error it seems there are still inconsistencies. Example project ID?

**Comment by Boegie** [comment]
@pjcdawkins Thanks for the explanation, makes sense.

Mailed you all my (28) non working project IDs

**Comment by pjcdawkins** [comment]
@Boegie Sorry, that one is a bug introduced in 3.40.1 (70ae5c09f2d111f59f8376184754879e5ebe6015) and resolved in 3.40.2 (cb50e4e17d1bb997db8518fb126f7f5898405a60)

**Comment by pjcdawkins** [comment]
Thanks for the quick reports and emails @tariqinaam @Boegie

**Comment by Boegie** [comment]
FWIW: 3.40.2 (not available at the time of my initial remark) did indeed solve my woes.
