### ISSUE TITLE
Composer error on install `Command "bin" is not defined.`

### ISSUE THREAD

**Issue by boombatower** [platformsh/platformsh-cli#791]
Starting with platformsh-cli version `3.40.6`.

```
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "bin" is not defined.                                   
                                                                  

Script @composer bin all install --ansi handling the post-install-cmd event returned with error code 1
```

I am assuming perhaps this requires a newer composer version? If so it would seem it should be communicated in deps or better yet avoided since I am running `1.8.4 2019-02-11 10:52:10` ~which is not exactly old~ (current apparently) and this is a change in a bugfix release.

**Comment by pjcdawkins** [comment]
Are you installing with --no-dev? The bin command is part of composer-bin-plugin, listed in dev requirements.

I can remove the script at best. Installing with --no-scripts would be a workaround

**Comment by boombatower** [comment]
Part of automated update script for building rpm package:

```bash
composer install --no-interaction --no-dev
```

Perhaps something needs to be explored there, but I'll use `--no-scripts` for now.

**Comment by boombatower** [comment]
Using platformsh-cli version `3.40.8` the issue no longer exists due to you removal commit. I am not sure what the purpose of the scripts is, so I'll leave it to you to close the issue if satisfied with that solution.
