### ISSUE TITLE
Improve the url picked when running e.g. platform drush uli

### ISSUE THREAD

**Issue by Berdir** [platformsh/platformsh-cli#819]
The platform drush command seems to pick an arbitrary url/domain, wondering if it would be possible to improve that. Sometimes that's a redirect or so that then doesn't really work.

In our own script, when connected, we pick one that is type upstream and contains `{default}` to make that more reliable, not sure if this is generic enough:

```
if (getenv('PLATFORM_ROUTES')) {
  $routes = json_decode(base64_decode(getenv('PLATFORM_ROUTES')), TRUE);
  foreach ($routes as $url => $route) {
    if ($route['type'] == 'upstream' && strpos($route['original_url'], '{default}') !== FALSE) {
      // Make sure that any trailing slashes are removed.
      $options['l'] = trim($url, '/');
      break;
    }
  }
}
```

Just putting this out here ;)

**Comment by pjcdawkins** [comment]
The `Api::getSiteUrl()` method is what selects the URL for `platform drush`. It only selects "upstream" routes that match the app name in question, so it can't select redirects.

https://github.com/platformsh/platformsh-cli/blob/26553764ae3cb45e8987a1903d08c987a28c0e15/src/Command/Environment/EnvironmentDrushCommand.php#L92-L95
https://github.com/platformsh/platformsh-cli/blob/26553764ae3cb45e8987a1903d08c987a28c0e15/src/Service/Api.php#L826-L840

**Comment by pjcdawkins** [comment]
as we now have the concept of a "primary" route, that PR would produce a predictable result ^

https://docs.platform.sh/configuration/routes.html#route-identifiers

**Comment by pjcdawkins** [comment]
It looks like it currently has a bug in that it doesn't match the upstream to the app correctly (it's expecting `appname` rather than `appname:http`)... so currently would fall back to the environment's "public URL" which is `http://<default domain>`. The above PR fixes that too.
