### ISSUE TITLE
drush "Command is not defined" (due to incorrect quoting)

### ISSUE THREAD

**Issue by danielnitsche** [platformsh/platformsh-cli#860]
Previously, I was able to do this:
`platform drush "cr -l mymultisite"`

On 3.49.1, if I try and run the same command, I get this:
`Command "cr -l mymultisite" is not defined.`

I'm assuming this got broken in: https://github.com/platformsh/platformsh-cli/commit/5a3ab4dd666a5636d05afb4e4e009c6d63b23ddd

Happy to change my syntax if there is another way to do this.

**Comment by danielnitsche** [comment]
Actually, I think more than just multisite is affected. Even the example command is not working for me:
`platform drush user-login --mail=name@example.com`
`The "--mail" option does not exist.`

`platform --environment=develop drush 'user-login --mail=name@example.com'`
`Command "user-login --mail=name@example.com" is not defined.`

**Comment by pjcdawkins** [comment]
There is a workaround for your syntax before #861 can be released:

```sh
platform drush -- cr -l mymultisite
```

**Comment by danielnitsche** [comment]
Great thanks. Might be good to get some test coverage on this if possible?

**Comment by pjcdawkins** [comment]
It would be good yes... for now it's fixed in version 3.49.2 (`platform up` to update)
