### ISSUE TITLE
The change of drush alias from absolute to relative, throws errors using sql-sync

### ISSUE THREAD

**Issue by sheanhoxie** [platformsh/platformsh-cli#873]
Drush version: 9.7.0
Error with platform-cli version: 3.49.3
resolves with platform-cli version: 3.49.2

Updating platform.cli to 3.49.3 and running platform drush-alias -r, removes the absolute path to the remote root, and running 
`drush sql-sync @alias_name.master @alias_name._local`

throws this error

```
The command "/Users/sheanhoxie/Sites/site-name/site-name/vendor/drush/drush/drush core-rsync @site-name.master:/app/drush-backups/main/20191121002727/main_20191121_002727.sql.gz @site-name._local:/tmp/main_20191121_002727.sql.gz --uri=default --root=/Users/sheanhoxie/Sites/site-name/site-name/web -- --remove-source-files" failed.

  Exit Code: 1(General error)

  Working directory:

  Output:
  ================
  Error Output:
  ================

  In Path.php line 587:

    The base path "web" is not an absolute path.
```

Downgrading to 3.49.2, and rebuilding aliases, or manually renaming the remote alias root to absolute path, resolves the issue.

I see here at  #869 that Drush is supposed to be ok with relative paths as of 9.6.2, but I am running 9.7.0 and am receiving errors.

**Comment by pjcdawkins** [comment]
Thanks. It seems Drush still has a problem with relative paths in `sql-sync` and `rsync` commands. Reverted (to absolute paths) in 3.50
