### ISSUE TITLE
Rsync command does not have the option to include an identity file

### ISSUE THREAD

**Issue by tylerssn** [platformsh/platformsh-cli#880]
`platform ssh` has the option to pass an identity file such as `-i id_rsa2`. It would be nice for `platform rsync` to include this as well.

**Comment by socketwench** [comment]
mount:upload and mount:download too.

**Comment by pjcdawkins** [comment]
PR above

@tylerssn is there a `platform rsync` command or did you also mean `mount:upload` and `mount:download`?

(there's also `platform scp`, which already allows the `-i` option)
