### ISSUE TITLE
RootNotFoundException when trying to ssh from outside a project

### ISSUE THREAD

**Issue by alexthunder3** [platformsh/platformsh-cli#948]
Hey guys,
noticed this Exception popping up nowadays. I used to run `platform ssh` from random terminals most of the times and it would bring up a list from where i could choose which project and branch to connect to. I've used `project:set-remote` to map my projects to the CLI tool, but I still enjoyed opening up a quick random terminal, running `platform ssh` and off i went. I get the reasoning for this, but wouldn't it be easier to add a short info message to use `platform:set-remote` if it's supposed to be a project root, instead of an Exception? That way everyone can use the commands however and wherever they wish.

Thanks for this awesome tool!
Kind regards,
Alex.

**Comment by pjcdawkins** [comment]
I'm confused. You should be able to open a random terminal, run `platform ssh`, and if you're not in a project directory then it should show you a list of your projects. Is that not what you're seeing? Did something change?

**Comment by alexthunder3** [comment]
I'm getting 
```
  [RootNotFoundException]                                    
  Could not determine the current project.                   
                                                             
  Specify it using --project, or go to a project directory. 
```
when running platform ssh in a random folder. Also ran platform cc, still the same output.

**Comment by pjcdawkins** [comment]
Here are the conditions on showing that project choice list:

https://github.com/platformsh/platformsh-cli/blob/8552ed3f17f28ef6504c599d4df707e7d294044e/src/Command/CommandBase.php#L754-L763

so choices will be shown if:

- no project ID supplied
- no "current" project (not in a project directory)
- input is interactive (you haven't used `--yes` or `--no` or `PLATFORMSH_CLI_NO_INTERACTION`)
- you have at least 1, and less than 25, projects in your list (i.e. you have access to >0 and <25 projects)

**Comment by alexthunder3** [comment]
Oh. Indeed I got up to 25 😒. Why 25 though?

**Comment by pjcdawkins** [comment]
It was just to avoid providing an overly long list - many terminals do not have many lines of height and not being able to see the top of the list (your original command and the "Enter a number to choose a project") would be confusing.

Maybe it could switch to a single-line autocomplete-style prompt, when there is a large number of projects.

**Comment by pjcdawkins** [comment]
If you have time, could you test that PR? ^ Use the "Testing instructions" on the automatically built Platform.sh environment - https://pr-949-gpxsbya-mpaw4nkgdwaea.eu-2.platformsh.site/

**Comment by alexthunder3** [comment]
Nice!
Would've been better if I could use project label/title since I don't know any of the id's, but up/down arrows does loop through and I can find the one I want. 
Gonna be a while until this gets live, right? I'll use this build for a while :grimacing: :heart_eyes: 
Thanks!

**Comment by pjcdawkins** [comment]
Right, it's not ideal, unfortunately the autocomplete only works with the start of the string, rather than searching within it (at least with symfony/console 3.x), so even with the title it would be difficult to find. It's case-sensitive too. So asking for the project ID seems the most consistent thing to do with that limitation.

https://github.com/symfony/symfony/blob/40152c37ce3c150ffa6a70d0dc44b8ea453fc840/src/Symfony/Component/Console/Helper/QuestionHelper.php#L352-L357

**Comment by alexthunder3** [comment]
Yea, the case sensitivity got me a few times. Then again, if i have to resort to scrolling anyway, i might hit a title faster than i would an id. Easier to remember which are the "black sheep" that start with uppercase and such. At least from personal experience. I know by title which how it starts, can't for the life of me remember first 3 characters of any project id.
Still a lot better than getting exception 😁😁

**Comment by pjcdawkins** [comment]
Right, this was released in https://github.com/platformsh/platformsh-cli/releases/tag/v3.61.0 - with the autocomplete limitation as discussed. Thanks for closing.
