### ISSUE TITLE
Bad configuration option: include; check ssh version?

### ISSUE THREAD

**Issue by andrewbaxter** [platformsh/platformsh-cli#966]
Troubleshot an issue where `platform get PROJ` was failing, and `-vvv` showed `/home/me/.ssh/config: line 2: Bad configuration option: include`.  Without verbose logging, the command failed with "fatal: Could not read from remote repository/Please make sure you have the correct access rights" which looks like a permissions issue and started a bit of a wild goose chase.

Googling says `include` is a new feature in ssh 7.3+, so I assume this will be fixed by upgrading ssh.  Would it be reasonable for the cli check the ssh version and display a warning if it's too old?  I think even something conservative, like warning on versions < 7.9 may provide a starting point for users to help themselves.

**Comment by pjcdawkins** [comment]
Ah right.. yes I wasn't aware of this one. So recent CLI versions introduce a few SSH requirements:

1. ed25519 keys/certificates (OpenSSH 6.5)
2. `CertificateFile` directive (7.2)
3. `Include` (7.3 as you point out)

Yes, good point, it should check and warn on a lower version, in the installer and in SSH commands.

**Comment by pjcdawkins** [comment]
I've added checks in version 3.60.2
