### ISSUE TITLE
`stderr` suppressed from `ls-remote` in `get`

### ISSUE THREAD

**Issue by andrewbaxter** [platformsh/platformsh-cli#967]
When running `platform get PROJ -vvv` `ls-remote` is run initially.  `LogLevel DEBUG` is set, however the stderr output for that command never makes it to the terminal.  If there's a connection issue the relevant diagnostic messages won't appear unless the user puts together the command pieces and runs `ls-remote` manually.

I know `stdout` is captured for `ls-remote`, but would it be possible to leave stderr unobstructed, or dump it to the terminal if the command fails?

**Comment by pjcdawkins** [comment]
It should be possible to see the stderr output now since [version 3.62.0](https://github.com/platformsh/platformsh-cli/releases/tag/v3.62.0) by running `platform get -vvv`
